In [112]:
import numpy as np
import pandas as pd
from numpy import isnan
#Accident data
Acc_01=pd.read_csv(r'E:\data ming\accident_prediction\NYC_data\accident data\full_data\acc_2017_gridid.csv')

In [113]:
Acc_01

,Unnamed: 0,MONTH,DAY,YEAR,TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,...,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,UNIQUE KEY,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,X,Y,grid_id,risk_level,Time
0,190557,1,1,2017,0:00,NaN,NaN,40.666435,-73.834780,"(40.666435, -73.83478)",...,Unspecified,NaN,3589973,PASSENGER VEHICLE,NaN,18,15,501,1,0.0000
1,191289,1,1,2017,12:30,NaN,NaN,40.711861,-73.978062,"(40.7118605, -73.9780625)",...,Pavement Defective,NaN,3591087,PASSENGER VEHICLE,NaN,14,7,385,1,0.5208
2,212579,1,1,2017,0:00,NaN,NaN,40.772331,-73.945304,"(40.7723306, -73.9453041)",...,Outside Car Distraction,Unspecified,3590766,PASSENGER VEHICLE,PASSENGER VEHICLE,10,9,279,1,0.0000
3,212659,1,1,2017,0:00,BROOKLYN,11210.0,40.632427,-73.940830,"(40.632427, -73.94083)",...,Unspecified,NaN,3821035,PASSENGER VEHICLE,NaN,20,9,549,1,0.0000
4,212660,1,1,2017,0:00,QUEENS,11385.0,40.700169,-73.909204,"(40.7001691, -73.9092037)",...,Unspecified,NaN,3590430,PASSENGER VEHICLE,NaN,15,11,416,1,0.0000
5,212661,1,1,2017,0:00,QUEENS,11385.0,40.703086,-73.859702,"(40.7030865, -73.8597025)",...,Unspecified,NaN,3590438,SPORT UTILITY / STATION WAGON,NaN,15,13,418,1,0.0000
6,212662,1,1,2017,0:00,MANHATTAN,10010.0,40.743116,-73.992667,"(40.7431162, -73.9926669)",...,Driver Inattention/Distraction,NaN,3593809,BICYCLE,NaN,12,6,330,3,0.0000
7,212663,1,1,2017,0:05,QUEENS,11433.0,40.696213,-73.782280,"(40.696213, -73.78228)",...,Unspecified,NaN,3610968,SPORT UTILITY / STATION WAGON,NaN,15,18,423,1,0.0035
8,212664,1,1,2017,0:20,BRONX,10453.0,40.849669,-73.908013,"(40.8496686, -73.9080129)",...,Unspecified,Unspecified,3590013,PASSENGER VEHICLE,PASSENGER VEHICLE,4,11,119,1,0.0139
9,212665,1,1,2017,0:30,BROOKLYN,11217.0,40.684183,-73.983952,"(40.6841826, -73.9839515)",...,Pavement Defective,NaN,3589962,PASSENGER VEHICLE,NaN,16,7,439,1,0.0208
10,212666,1,1,2017,0:30,BROOKLYN,11236.0,40.636593,-73.894172,"(40.6365927, -73.8941719)",...,Failure to Yield Right-of-Way,Unspecified,3590601,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON,20,11,551,1,0.0208
11,212667,1,1,2017,0:30,QUEENS,11428.0,40.722315,-73.742842,"(40.722315, -73.742842)",...,Alcohol Involvement,Unspecified,3590058,PASSENGER VEHICLE,PASSENGER VEHICLE,13,20,371,1,0.0208
12,212668,1,1,2017,0:30,NaN,NaN,40.677498,-73.913620,"(40.677498, -73.91362)",...,Unspecified,NaN,3609065,PASSENGER VEHICLE,NaN,17,10,469,1,0.0208
13,212669,1,1,2017,0:40,NaN,NaN,40.689686,-73.890290,"(40.689686, -73.89029)",...,Outside Car Distraction,Unspecified,3590644,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE,16,12,444,1,0.0278
14,212670,1,1,2017,0:45,BROOKLYN,11210.0,40.624800,-73.942646,"(40.6247998, -73.9426464)",...,Unspecified,Unspecified,3591146,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE,21,9,576,1,0.0313
15,212672,1,1,2017,10:00,BROOKLYN,11218.0,40.646636,-73.981215,"(40.6466364, -73.9812146)",...,Unspecified,Unspecified,3591511,SPORT UTILITY / STATION WAGON,NaN,19,7,520,1,0.4167
16,212673,1,1,2017,10:00,MANHATTAN,10002.0,40.721723,-73.987536,"(40.7217232, -73.9875356)",...,Driver Inattention/Distraction,NaN,3591086,PASSENGER VEHICLE,NaN,13,6,357,1,0.4167
17,212674,1,1,2017,10:00,QUEENS,11366.0,40.733130,-73.783025,"(40.7331298, -73.7830252)",...,Driver Inattention/Distraction,Unspecified,3590069,PASSENGER VEHICLE,PASSENGER VEHICLE,13,18,369,1,0.4167
18,212675,1,1,2017,10:00,NaN,NaN,40.823833,-73.876232,"(40.8238325, -73.876232)",...,Unsafe Speed,Unspecified,3590619,PASSENGER VEHICLE,PASSENGER VEHICLE,6,12,174,1,0.4167
19,212676,1,1,2017,10:10,QUEENS,11106.0,40.764349,-73.923458,"(40.7643491, -73.9234585)",...,Unsafe Speed,Unspecified,3590754,SPORT UTILITY / STATION WAGON,SPORT UTILITY / STATION WAGON,10,10,280,3,0.4236
20,212677,1,1,2017,10:20,QUEENS,11372.0,40.751004,-73.892121,"(40.7510038, -73.8921206)",...,Unspecified,Unspecified,3596737,TAXI,TAXI,11,12,309,1,0.4306
21,212678,1,1,2017,10:30,BROOKLYN,11207.0,40.682179,-73.888958,"(40.6821786, -73.8889581)",...,Other Vehicular,NaN,3590858,PASSENGER VEHICLE,NaN,16,12,444,1,0.4375
22,212679,1,1,2017,10:30,BROOKLYN,11229.0,40.606640,-73.940510,"(40.60664, -73.94051)",...,Following Too Closely,Unspecified,3591179,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE,22,9,603,1,0.4375
23,212680,1,1,2017,10:30,QUEENS,11432.0,40.710847,-73.782488,"(40.7108467, -73.7824881)",...,Driver Inattention/Distraction,Driver Inattention/Distraction,3590292,SPORT UTILITY / STATION WAGON,NaN,14,18,396,1,0.4375
24,212681,1,1,2017,10:55,BROOKLYN,11210.0,40.614224,-73.947428,"(40.6142236, -73.9474279)",...,Backing Unsafely,Unspecified,3592940,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE,21,9,576,1,0.4549
25,212682,1,1,2017,11:00,BROOKLYN,11211.0,40.716172,-73.959511,"(40.7161723, -73.9595114)",...,Unspecified,Unspecified,3590244,PASSENGER VEHICLE,NaN,14,8,386,1,0.4583
26,212683,1,1,2017,11:00,BROOKLYN,11223.0,40.605692,-73.980283,"(40.6056922, -73.9802826)",...,Following Too Closely,Unspecified,3590349,PASSENGER VEHICLE,PASSENGER VEHICLE,22,7,601,1,0.4583
27,212684,1,1,2017,11:00,QUEENS,11426.0,40.725949,-73.721477,"(40.7259488, -73.7214766)",...,Driver Inattention/Distraction,Unspecified,3590057,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE,13,21,372,1,0.4583
28,212685,1,1,2017,11:01,MANHATTAN,10017.0,40.751122,-73.971263,"(40.7511221, -73.9712634)",...,Driver Inattention/Distraction,Following Too Closely,3590173,SPORT UTILITY / STATION WAGON,SPORT UTILITY / STATION WAGON,11,7,304,1,0.4590
29,212686,1,1,2017,11:20,BROOKLYN,11225.0,40.663475,-73.957777,"(40.6634749, -73.9577772)",...,Unspecified,NaN,3590999,PASSENGER VEHICLE,PASSENGER VEHICLE,18,8,494,1,0.4722
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201145,394,12,31,2017,7:25,NaN,NaN,40.744892,-73.770220,"(40.744892, -73.77022)",...,Driver Inattention/Distraction,Other Vehicular,3818629,PASSENGER VEHICLE,DS,12,18,342,3,0.3090
201146,395,12,31,2017,7:50,NaN,NaN,40.668648,-73.928350,"(40.668648, -73.92835)",...,Driver Inattention/Distraction,NaN,3820526,PASSENGER VEHICLE,NaN,17,10,469,1,0.3264
201147,396,12,31,2017,8:05,NaN,NaN,40.774612,-73.923990,"(40.774612, -73.92399)",...,Following Too Closely,Unspecified,3819717,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON,10,10,280,1,0.3368
201148,397,12,31,2017,8:10,BROOKLYN,11226.0,40.650414,-73.957980,"(40.650414, -73.95798)",...,Driver Inattention/Distraction,Unspecified,3819300,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE,19,8,521,1,0.3403
201149,398,12,31,2017,8:15,BROOKLYN,11203.0,40.656708,-73.929640,"(40.656708, -73.92964)",...,Unspecified,Unspecified,3819195,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE,18,10,496,1,0.3438
201150,399,12,31,2017,8:25,NaN,NaN,40.744892,-73.770220,"(40.744892, -73.77022)",...,Following Too Closely,Unspecified,3818630,PASSENGER VEHICLE,DS,12,18,342,1,0.3507
201151,400,12,31,2017,8:26,BROOKLYN,11213.0,40.663605,-73.934395,"(40.663605, -73.934395)",...,Driver Inattention/Distraction,Unspecified,3820523,SPORT UTILITY / STATION WAGON,SPORT UTILITY / STATION WAGON,18,9,495,1,0.3514
201152,401,12,31,2017,8:30,BROOKLYN,11234.0,40.621483,-73.925200,"(40.621483, -73.9252)",...,Unspecified,NaN,3820942,PASSENGER VEHICLE,NaN,21,10,577,1,0.3542
201153,402,12,31,2017,8:30,QUEENS,11368.0,40.749866,-73.862730,"(40.749866, -73.86273)",...,Unspecified,Unspecified,3821622,DS,PASSENGER VEHICLE,11,13,310,1,0.3542
201154,403,12,31,2017,8:30,BROOKLYN,11201.0,40.694790,-73.994310,"(40.69479, -73.99431)",...,Traffic Control Disregarded,Traffic Control Disregarded,3820512,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE,15,6,411,2,0.3542
201155,404,12,31,2017,8:30,BROOKLYN,11249.0,40.722836,-73.956870,"(40.722836, -73.95687)",...,Pavement Slippery,Unspecified,3820515,PASSENGER VEHICLE,PASSENGER VEHICLE,13,8,359,3,0.3542
201156,405,12,31,2017,8:35,NaN,NaN,40.761353,-73.935394,"(40.761353, -73.935394)",...,Pavement Slippery,Unspecified,3819718,SPORT UTILITY / STATION WAGON,PICK-UP TRUCK,11,9,306,1,0.3576
201157,406,12,31,2017,8:35,NaN,NaN,40.673008,-73.788090,"(40.673008, -73.78809)",...,Unsafe Lane Changing,Unspecified,3820520,PASSENGER VEHICLE,PASSENGER VEHICLE,17,17,476,1,0.3576
201158,407,12,31,2017,8:40,QUEENS,11375.0,40.717170,-73.834970,"(40.71717, -73.83497)",...,Following Too Closely,Unspecified,3818755,TAXI,PASSENGER VEHICLE,14,15,393,1,0.3611
201159,408,12,31,2017,8:50,NaN,NaN,40.855770,-73.825500,"(40.85577, -73.8255)",...,Driver Inexperience,Unspecified,3818958,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE,4,15,123,1,0.3681
201160,409,12,31,2017,9:00,QUEENS,11420.0,40.684597,-73.813940,"(40.684597, -73.81394)",...,Driver Inattention/Distraction,Unspecified,3819137,PASSENGER VEHICLE,PASSENGER VEHICLE,16,16,448,1,0.3750
201161,410,12,31,2017,9:04,BRONX,10459.0,40.830124,-73.889915,"(40.830124, -73.889915)",...,Pavement Slippery,Unspecified,3821077,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON,6,12,174,1,0.3778
201162,411,12,31,2017,9:09,BROOKLYN,11222.0,40.730705,-73.948840,"(40.730705, -73.94884)",...,Backing Unsafely,Unspecified,3820606,PASSENGER VEHICLE,TK,13,8,359,1,0.3813
201163,413,12,31,2017,9:11,BRONX,10467.0,40.884014,-73.879100,"(40.884014, -73.8791)",...,Failure to Yield Right-of-Way,Unspecified,3820613,SPORT UTILITY / STATION WAGON,SPORT UTILITY / STATION WAGON,2,12,66,1,0.3826
201164,414,12,31,2017,9:15,BROOKLYN,11233.0,40.679260,-73.928600,"(40.67926, -73.9286)",...,Unspecified,NaN,3820831,BU,TAXI,17,10,469,1,0.3854
201165,415,12,31,2017,9:17,BROOKLYN,11212.0,40.654710,-73.907110,"(40.65471, -73.90711)",...,Backing Unsafely,Unspecified,3818912,SPORT UTILITY / STATION WAGON,SPORT UTILITY / STATION WAGON,18,11,497,1,0.3868
201166,417,12,31,2017,9:21,BROOKLYN,11234.0,40.628350,-73.924965,"(40.62835, -73.924965)",...,Unspecified,Unspecified,3821366,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE,20,10,550,1,0.3896
201167,418,12,31,2017,9:30,BROOKLYN,11212.0,40.666393,-73.921590,"(40.666393, -73.92159)",...,Unspecified,Unspecified,3822637,PASSENGER VEHICLE,PASSENGER VEHICLE,18,10,496,1,0.3958
201168,419,12,31,2017,9:30,QUEENS,11366.0,40.727657,-73.796640,"(40.727657, -73.79664)",...,Unsafe Speed,Traffic Control Disregarded,3819306,PASSENGER VEHICLE,PASSENGER VEHICLE,13,17,368,1,0.3958
201169,420,12,31,2017,9:30,QUEENS,11691.0,40.595820,-73.772330,"(40.59582, -73.77233)",...,Unspecified,NaN,3821003,PASSENGER VEHICLE,NaN,23,18,639,1,0.3958
201170,423,12,31,2017,9:30,QUEENS,11355.0,40.746143,-73.827180,"(40.746143, -73.82718)",...,Failure to Yield Right-of-Way,NaN,3819357,SPORT UTILITY / STATION WAGON,NaN,12,15,339,2,0.3958
201171,424,12,31,2017,9:32,MANHATTAN,10019.0,40.762220,-73.978750,"(40.76222, -73.97875)",...,Failure to Yield Right-of-Way,Failure to Yield Right-of-Way,3821298,TAXI,PASSENGER VEHICLE,11,7,304,1,0.3972
201172,426,12,31,2017,9:45,MANHATTAN,10019.0,40.764030,-73.982475,"(40.76403, -73.982475)",...,Backing Unsafely,Unspecified,3821658,PASSENGER VEHICLE,BU,10,7,277,1,0.4063
201173,427,12,31,2017,9:45,NaN,NaN,40.626600,-73.982710,"(40.6266, -73.98271)",...,Failure to Yield Right-of-Way,Unsafe Speed,3822507,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON,20,7,547,1,0.4063
201174,428,12,31,2017,9:50,BROOKLYN,11226.0,40.650806,-73.949580,"(40.650806, -73.94958)",...,Unspecified,NaN,3826908,PASSENGER VEHICLE,NaN,19,8,521,1,0.4097

In [116]:
Acc_01m['MONTH']

13412    2
13413    2
13414    2
13415    2
13416    2
13417    2
13418    2
13419    2
13420    2
13421    2
13422    2
13423    2
13424    2
13425    2
13426    2
13427    2
13428    2
13429    2
13430    2
13431    2
13432    2
13433    2
13434    2
13435    2
13436    2
13437    2
13438    2
13439    2
13440    2
13441    2
        ..
27334    2
27335    2
27336    2
27337    2
27338    2
27339    2
27340    2
27341    2
27342    2
27343    2
27344    2
27345    2
27346    2
27347    2
27348    2
27349    2
27350    2
27351    2
27352    2
27353    2
27354    2
27355    2
27356    2
27357    2
27358    2
27359    2
27360    2
27361    2
27362    2
27363    2
Name: MONTH, Length: 13952, dtype: int64

In [150]:
Month_day = [31,28,31,30,31,30,31,31,30,31,30,31]

In [200]:
month_num = 5
Acc_01m=Acc_01[Acc_01['MONTH']==month_num]

In [201]:
'%02d'%month_num

'05'

In [202]:
Acc_01m['Interval_10']=np.int32(Acc_01m['Time']*1440/10)
Acc_01m['Interval_20']=np.int32(Acc_01m['Time']*1440/20)
Acc_01m['Interval_30']=np.int32(Acc_01m['Time']*1440/30)
Acc_01m['Interval_60']=np.int32(Acc_01m['Time']*1440/60)

c:\users\dell\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
c:\users\dell\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

c:\users\dell\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
c:\users\dell\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [203]:
Acc_01m

,Unnamed: 0,MONTH,DAY,YEAR,TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,...,VEHICLE TYPE CODE 2,X,Y,grid_id,risk_level,Time,Interval_10,Interval_20,Interval_30,Interval_60
60389,148509,5,1,2017,0:00,BRONX,10451.0,40.826540,-73.915320,"(40.82654, -73.91532)",...,SPORT UTILITY / STATION WAGON,6,10,172,1,0.0000,0,0,0,0
60390,148510,5,1,2017,0:00,BRONX,10463.0,40.880380,-73.910910,"(40.88038, -73.91091)",...,PASSENGER VEHICLE,2,11,65,1,0.0000,0,0,0,0
60391,148511,5,1,2017,0:00,BRONX,10466.0,40.881897,-73.837130,"(40.881897, -73.83713)",...,PASSENGER VEHICLE,2,15,69,1,0.0000,0,0,0,0
60392,148512,5,1,2017,0:00,BRONX,10468.0,40.861650,-73.910760,"(40.86165, -73.91076)",...,NaN,3,11,92,1,0.0000,0,0,0,0
60393,148513,5,1,2017,0:00,MANHATTAN,10011.0,40.739857,-73.993195,"(40.739857, -73.993195)",...,PASSENGER VEHICLE,12,6,330,1,0.0000,0,0,0,0
60394,148514,5,1,2017,0:00,MANHATTAN,10024.0,40.781837,-73.979294,"(40.781837, -73.979294)",...,SPORT UTILITY / STATION WAGON,9,7,250,1,0.0000,0,0,0,0
60395,148515,5,1,2017,0:00,QUEENS,11373.0,40.747510,-73.876790,"(40.74751, -73.87679)",...,SPORT UTILITY / STATION WAGON,12,12,336,1,0.0000,0,0,0,0
60396,148516,5,1,2017,0:00,QUEENS,11427.0,40.729940,-73.744810,"(40.72994, -73.74481)",...,SPORT UTILITY / STATION WAGON,13,20,371,1,0.0000,0,0,0,0
60397,148517,5,1,2017,0:00,NaN,NaN,40.672382,-73.785740,"(40.672382, -73.78574)",...,PASSENGER VEHICLE,17,17,476,1,0.0000,0,0,0,0
60398,148518,5,1,2017,0:00,NaN,NaN,40.691680,-73.999344,"(40.69168, -73.999344)",...,SPORT UTILITY / STATION WAGON,16,6,438,1,0.0000,0,0,0,0
60399,148519,5,1,2017,0:00,BROOKLYN,11226.0,40.644943,-73.948940,"(40.644943, -73.94894)",...,PASSENGER VEHICLE,19,8,521,2,0.0000,0,0,0,0
60400,148520,5,1,2017,0:10,MANHATTAN,10001.0,40.750988,-73.990630,"(40.750988, -73.99063)",...,TAXI,11,6,303,1,0.0069,0,0,0,0
60401,148521,5,1,2017,0:10,MANHATTAN,10034.0,40.865547,-73.927280,"(40.865547, -73.92728)",...,SPORT UTILITY / STATION WAGON,3,10,91,1,0.0069,0,0,0,0
60402,148522,5,1,2017,0:20,MANHATTAN,10018.0,40.757732,-73.996860,"(40.757732, -73.99686)",...,NaN,11,6,303,1,0.0139,2,1,0,0
60403,148523,5,1,2017,0:37,NaN,NaN,40.824130,-73.940980,"(40.82413, -73.94098)",...,SPORT UTILITY / STATION WAGON,6,9,171,1,0.0257,3,1,1,0
60404,148524,5,1,2017,0:50,BRONX,10469.0,40.873047,-73.857060,"(40.873047, -73.85706)",...,PASSENGER VEHICLE,2,13,67,1,0.0347,4,2,1,0
60405,148525,5,1,2017,10:00,BRONX,10469.0,40.871204,-73.854965,"(40.871204, -73.854965)",...,NaN,3,14,95,1,0.4167,60,30,20,10
60406,148526,5,1,2017,10:00,BROOKLYN,11236.0,40.640460,-73.901220,"(40.64046, -73.90122)",...,SPORT UTILITY / STATION WAGON,19,11,524,1,0.4167,60,30,20,10
60407,148527,5,1,2017,10:00,QUEENS,11357.0,40.795430,-73.826355,"(40.79543, -73.826355)",...,NaN,8,15,231,1,0.4167,60,30,20,10
60408,148529,5,1,2017,10:00,NaN,NaN,40.854874,-73.916794,"(40.854874, -73.916794)",...,NaN,4,10,118,1,0.4167,60,30,20,10
60409,148530,5,1,2017,10:00,MANHATTAN,10010.0,40.738470,-73.987640,"(40.73847, -73.98764)",...,PASSENGER VEHICLE,12,6,330,2,0.4167,60,30,20,10
60410,148531,5,1,2017,10:15,BROOKLYN,11210.0,40.627810,-73.933655,"(40.62781, -73.933655)",...,PASSENGER VEHICLE,20,9,549,1,0.4271,61,30,20,10
60411,148532,5,1,2017,10:15,BROOKLYN,11210.0,40.631580,-73.947550,"(40.63158, -73.94755)",...,PASSENGER VEHICLE,20,9,549,1,0.4271,61,30,20,10
60412,148533,5,1,2017,10:15,BROOKLYN,11225.0,40.661385,-73.953620,"(40.661385, -73.95362)",...,SPORT UTILITY / STATION WAGON,18,8,494,1,0.4271,61,30,20,10
60413,148534,5,1,2017,10:15,QUEENS,11420.0,40.670864,-73.807530,"(40.670864, -73.80753)",...,PASSENGER VEHICLE,17,16,475,1,0.4271,61,30,20,10
60414,148535,5,1,2017,10:15,QUEENS,11692.0,40.592052,-73.789660,"(40.592052, -73.78966)",...,PASSENGER VEHICLE,23,17,638,1,0.4271,61,30,20,10
60415,148536,5,1,2017,10:17,NaN,NaN,40.778614,-73.839770,"(40.778614, -73.83977)",...,SPORT UTILITY / STATION WAGON,9,14,257,5,0.4285,61,30,20,10
60416,148537,5,1,2017,10:18,NaN,NaN,40.873060,-73.878640,"(40.87306, -73.87864)",...,PASSENGER VEHICLE,2,12,66,1,0.4292,61,30,20,10
60417,148538,5,1,2017,10:24,NaN,NaN,40.767680,-73.982160,"(40.76768, -73.98216)",...,PASSENGER VEHICLE,10,7,277,1,0.4333,62,31,20,10
60418,148541,5,1,2017,10:25,NaN,NaN,40.678574,-74.003580,"(40.678574, -74.00358)",...,NaN,17,6,465,1,0.4340,62,31,20,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79052,129983,5,31,2017,9:05,BROOKLYN,11219.0,40.630924,-74.003560,"(40.630924, -74.00356)",...,BICYCLE,20,6,546,2,0.3785,54,27,18,9
79053,129984,5,31,2017,9:10,NaN,NaN,40.832140,-73.927290,"(40.83214, -73.92729)",...,SPORT UTILITY / STATION WAGON,5,10,145,1,0.3819,54,27,18,9
79054,129985,5,31,2017,9:10,NaN,NaN,40.702675,-73.933960,"(40.702675, -73.93396)",...,NaN,15,9,414,1,0.3819,54,27,18,9
79055,129986,5,31,2017,9:10,QUEENS,11434.0,40.680490,-73.774704,"(40.68049, -73.774704)",...,NaN,17,18,477,2,0.3819,54,27,18,9
79056,129987,5,31,2017,9:14,NaN,NaN,40.762394,-73.978610,"(40.762394, -73.97861)",...,BICYCLE,11,7,304,1,0.3847,55,27,18,9
79057,129988,5,31,2017,9:15,BROOKLYN,11210.0,40.623875,-73.935470,"(40.623875, -73.93547)",...,SPORT UTILITY / STATION WAGON,21,9,576,1,0.3854,55,27,18,9
79058,129989,5,31,2017,9:15,MANHATTAN,10029.0,40.790417,-73.951840,"(40.790417, -73.95184)",...,NaN,8,8,224,2,0.3854,55,27,18,9
79059,129990,5,31,2017,9:16,QUEENS,11416.0,40.686237,-73.839066,"(40.686237, -73.839066)",...,PASSENGER VEHICLE,16,14,446,1,0.3861,55,27,18,9
79060,129991,5,31,2017,9:20,QUEENS,11362.0,40.755760,-73.739390,"(40.75576, -73.73939)",...,PASSENGER VEHICLE,11,20,317,1,0.3889,56,28,18,9
79061,129993,5,31,2017,9:23,QUEENS,11432.0,40.706360,-73.792534,"(40.70636, -73.792534)",...,NaN,15,17,422,3,0.3910,56,28,18,9
79062,129994,5,31,2017,9:25,MANHATTAN,10035.0,40.806107,-73.940390,"(40.806107, -73.94039)",...,SPORT UTILITY / STATION WAGON,7,9,198,1,0.3924,56,28,18,9
79063,129995,5,31,2017,9:25,MANHATTAN,10075.0,40.774277,-73.959404,"(40.774277, -73.959404)",...,PASSENGER VEHICLE,10,8,278,1,0.3924,56,28,18,9
79064,129996,5,31,2017,9:25,NaN,NaN,40.749800,-73.952030,"(40.7498, -73.95203)",...,NaN,11,8,305,1,0.3924,56,28,18,9
79065,129997,5,31,2017,9:30,MANHATTAN,10027.0,40.808970,-73.948330,"(40.80897, -73.94833)",...,NaN,7,9,198,1,0.3958,56,28,18,9
79066,129998,5,31,2017,9:30,QUEENS,11436.0,40.683594,-73.803450,"(40.683594, -73.80345)",...,PASSENGER VEHICLE,16,16,448,1,0.3958,56,28,18,9
79067,129999,5,31,2017,9:30,NaN,NaN,40.759148,-73.793230,"(40.759148, -73.79323)",...,SPORT UTILITY / STATION WAGON,11,17,314,1,0.3958,56,28,18,9
79068,130000,5,31,2017,9:30,NaN,NaN,40.665836,-73.757390,"(40.665836, -73.75739)",...,PASSENGER VEHICLE,18,19,505,1,0.3958,56,28,18,9
79069,130001,5,31,2017,9:30,BRONX,10466.0,40.900574,-73.840050,"(40.900574, -73.84005)",...,NaN,0,14,14,2,0.3958,56,28,18,9
79070,130002,5,31,2017,9:30,BROOKLYN,11235.0,40.583668,-73.948430,"(40.583668, -73.94843)",...,SPORT UTILITY / STATION WAGON,24,9,657,2,0.3958,56,28,18,9
79071,130003,5,31,2017,9:30,MANHATTAN,10016.0,40.740643,-73.975810,"(40.740643, -73.97581)",...,PASSENGER VEHICLE,12,7,331,2,0.3958,56,28,18,9
79072,130004,5,31,2017,9:32,QUEENS,11354.0,40.769283,-73.824450,"(40.769283, -73.82445)",...,PASSENGER VEHICLE,10,15,285,1,0.3972,57,28,19,9
79073,130005,5,31,2017,9:40,MANHATTAN,10022.0,40.760350,-73.967460,"(40.76035, -73.96746)",...,NaN,11,7,304,1,0.4028,58,29,19,9
79074,130006,5,31,2017,9:40,BROOKLYN,11213.0,40.668797,-73.931130,"(40.668797, -73.93113)",...,PASSENGER VEHICLE,17,9,468,2,0.4028,58,29,19,9
79075,130007,5,31,2017,9:42,NaN,NaN,40.754677,-73.975815,"(40.754677, -73.975815)",...,TAXI,11,7,304,1,0.4042,58,29,19,9
79076,130008,5,31,2017,9:45,BROOKLYN,11231.0,40.684430,-73.994910,"(40.68443, -73.99491)",...,PICK-UP TRUCK,16,6,438,1,0.4063,58,29,19,9
79077,130009,5,31,2017,9:45,MANHATTAN,10019.0,40.760750,-73.979830,"(40.76075, -73.97983)",...,SPORT UTILITY / STATION WAGON,11,7,304,1,0.4063,58,29,19,9
79078,130010,5,31,2017,9:45,MANHATTAN,10036.0,40.757336,-73.989730,"(40.757336, -73.98973)",...,PASSENGER VEHICLE,11,6,303,1,0.4063,58,29,19,9
79079,130011,5,31,2017,9:45,NaN,NaN,40.848328,-73.918420,"(40.848328, -73.91842)",...,PICK-UP TRUCK,4,10,118,2,0.4063,58,29,19,9
79080,130012,5,31,2017,9:55,QUEENS,11358.0,40.755770,-73.788270,"(40.75577, -73.78827)",...,SPORT UTILITY / STATION WAGON,11,17,314,1,0.4132,59,29,19,9
79081,130014,5,31,2017,9:58,BRONX,10463.0,40.880817,-73.908410,"(40.880817, -73.90841)",...,NaN,2,11,65,1,0.4153,59,29,19,9

In [204]:
Acc_01m = Acc_01m.drop(columns=['OFF STREET NAME','LOCATION','ON STREET NAME','CROSS STREET NAME','BOROUGH', 'ZIP CODE','LATITUDE','LONGITUDE','CONTRIBUTING FACTOR VEHICLE 1','CONTRIBUTING FACTOR VEHICLE 2','UNIQUE KEY','VEHICLE TYPE CODE 1','VEHICLE TYPE CODE 2'])
Acc_01m['Risk_level']=1+Acc_01m['NUMBER OF PERSONS INJURED']+2*Acc_01m['NUMBER OF PERSONS KILLED']
Acc_01m = Acc_01m.sort_values(['DAY','Time'],ascending= [True,True])

In [205]:
pd.DataFrame(Acc_01m).to_csv(r'E:\data ming\accident_prediction\NYC_data\Experimental_data\Acc_speed_taxi_01_finegrained\Acc_'+'%02d'%month_num+'m.csv')

In [206]:
Acc_01m=pd.read_csv(r'E:\data ming\accident_prediction\NYC_data\Experimental_data\Acc_speed_taxi_01_finegrained\Acc_'+'%02d'%month_num+'m.csv')

In [207]:
Acc_01m

,Unnamed: 0,Unnamed: 0.1,MONTH,DAY,YEAR,TIME,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS KILLED,X,Y,grid_id,risk_level,Time,Interval_10,Interval_20,Interval_30,Interval_60,Risk_level
0,60389,148509,5,1,2017,0:00,0,0,6,10,172,1,0.0000,0,0,0,0,1
1,60390,148510,5,1,2017,0:00,0,0,2,11,65,1,0.0000,0,0,0,0,1
2,60391,148511,5,1,2017,0:00,0,0,2,15,69,1,0.0000,0,0,0,0,1
3,60392,148512,5,1,2017,0:00,0,0,3,11,92,1,0.0000,0,0,0,0,1
4,60393,148513,5,1,2017,0:00,0,0,12,6,330,1,0.0000,0,0,0,0,1
5,60394,148514,5,1,2017,0:00,0,0,9,7,250,1,0.0000,0,0,0,0,1
6,60395,148515,5,1,2017,0:00,0,0,12,12,336,1,0.0000,0,0,0,0,1
7,60396,148516,5,1,2017,0:00,0,0,13,20,371,1,0.0000,0,0,0,0,1
8,60397,148517,5,1,2017,0:00,0,0,17,17,476,1,0.0000,0,0,0,0,1
9,60398,148518,5,1,2017,0:00,0,0,16,6,438,1,0.0000,0,0,0,0,1
10,60399,148519,5,1,2017,0:00,1,0,19,8,521,2,0.0000,0,0,0,0,2
11,60400,148520,5,1,2017,0:10,0,0,11,6,303,1,0.0069,0,0,0,0,1
12,60401,148521,5,1,2017,0:10,0,0,3,10,91,1,0.0069,0,0,0,0,1
13,60402,148522,5,1,2017,0:20,0,0,11,6,303,1,0.0139,2,1,0,0,1
14,60403,148523,5,1,2017,0:37,0,0,6,9,171,1,0.0257,3,1,1,0,1
15,60404,148524,5,1,2017,0:50,0,0,2,13,67,1,0.0347,4,2,1,0,1
16,60760,148915,5,1,2017,1:08,0,0,0,14,14,1,0.0472,6,3,2,1,1
17,60761,148916,5,1,2017,1:40,2,0,6,12,174,3,0.0694,9,4,3,1,3
18,60762,148917,5,1,2017,1:45,0,0,3,13,94,1,0.0729,10,5,3,1,1
19,60763,148918,5,1,2017,1:50,0,0,4,10,118,1,0.0764,11,5,3,1,1
20,60819,148977,5,1,2017,2:00,0,0,16,14,446,1,0.0833,11,5,3,1,1
21,60820,148978,5,1,2017,2:14,0,0,20,12,552,1,0.0931,13,6,4,2,1
22,60821,148979,5,1,2017,3:07,1,0,2,12,66,2,0.1299,18,9,6,3,2
23,60822,148980,5,1,2017,3:10,0,0,16,16,448,1,0.1319,18,9,6,3,1
24,60823,148981,5,1,2017,3:31,0,0,5,9,144,1,0.1465,21,10,7,3,1
25,60824,148982,5,1,2017,3:42,0,0,14,6,384,1,0.1542,22,11,7,3,1
26,60825,148983,5,1,2017,3:50,0,0,21,6,573,1,0.1597,22,11,7,3,1
27,60826,148984,5,1,2017,3:55,0,0,6,10,172,1,0.1632,23,11,7,3,1
28,60828,148986,5,1,2017,4:00,1,0,11,13,310,2,0.1667,24,12,8,4,2
29,60829,148987,5,1,2017,4:31,1,0,3,15,96,2,0.1882,27,13,9,4,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18663,78906,129829,5,31,2017,21:45,1,0,16,7,439,2,0.9063,130,65,43,21,2
18664,78907,129830,5,31,2017,21:50,0,0,1,13,40,1,0.9097,130,65,43,21,1
18665,78908,129831,5,31,2017,21:50,0,0,13,17,368,1,0.9097,130,65,43,21,1
18666,78909,129832,5,31,2017,22:00,0,0,24,7,655,1,0.9167,132,66,44,22,1
18667,78910,129833,5,31,2017,22:00,0,0,10,15,285,1,0.9167,132,66,44,22,1
18668,78911,129834,5,31,2017,22:00,1,0,4,10,118,2,0.9167,132,66,44,22,2
18669,78912,129835,5,31,2017,22:06,0,0,22,4,598,1,0.9208,132,66,44,22,1
18670,78913,129836,5,31,2017,22:19,0,0,16,8,440,1,0.9299,133,66,44,22,1
18671,78914,129837,5,31,2017,22:20,0,0,10,12,282,1,0.9306,134,67,44,22,1
18672,78915,129838,5,31,2017,22:25,0,0,23,6,627,1,0.9340,134,67,44,22,1
18673,78916,129839,5,31,2017,22:30,0,0,6,9,171,1,0.9375,135,67,45,22,1
18674,78917,129840,5,31,2017,22:30,0,0,18,14,500,1,0.9375,135,67,45,22,1
18675,78918,129841,5,31,2017,22:35,0,0,7,9,198,1,0.9410,135,67,45,22,1
18676,78919,129842,5,31,2017,22:40,0,0,3,14,95,1,0.9444,135,67,45,22,1
18677,78920,129843,5,31,2017,22:40,1,0,9,7,250,2,0.9444,135,67,45,22,2
18678,78921,129844,5,31,2017,22:43,0,0,16,7,439,1,0.9465,136,68,45,22,1
18679,78922,129845,5,31,2017,22:47,1,0,11,8,305,2,0.9493,136,68,45,22,2
18680,78923,129846,5,31,2017,22:49,0,0,14,19,397,1,0.9507,136,68,45,22,1
18681,78924,129847,5,31,2017,22:52,0,0,6,12,174,1,0.9528,137,68,45,22,1
18682,78925,129848,5,31,2017,23:00,2,0,11,10,307,3,0.9583,137,68,45,22,3
18683,78926,129849,5,31,2017,23:05,0,0,15,15,420,1,0.9618,138,69,46,23,1
18684,78927,129850,5,31,2017,23:10,0,0,6,13,175,1,0.9653,139,69,46,23,1
18685,78928,129851,5,31,2017,23:10,3,0,5,13,148,4,0.9653,139,69,46,23,4
18686,78929,129852,5,31,2017,23:23,2,0,17,10,469,3,0.9743,140,70,46,23,3
18687,78930,129853,5,31,2017,23:23,2,0,17,10,469,3,0.9743,140,70,46,23,3
18688,78931,129854,5,31,2017,23:30,0,0,2,11,65,1,0.9792,141,70,47,23,1
18689,78932,129855,5,31,2017,23:30,0,0,11,12,309,1,0.9792,141,70,47,23,1
18690,78933,129856,5,31,2017,23:45,1,0,16,15,447,2,0.9896,142,71,47,23,2
18691,78934,129857,5,31,2017,23:50,0,0,10,6,276,1,0.9931,143,71,47,23,1
18692,78935,129859,5,31,2017,23:55,0,0,4,13,121,1,0.9965,143,71,47,23,1

In [208]:
day_num= Month_day[month_num-1]
day_num

31

In [209]:
speed_dataset2=Acc_01m
Interval=10 #10分钟
day_num= Month_day[month_num-1]
num_interval=np.int(1440/Interval) #一天里多少interval
Total_interval=day_num*num_interval
speed_halfhour= np.zeros([day_num,num_interval,729])#生成数组保存每组速度
kk=0
s=0
for ii in range(0,day_num):  
    speed_dataset=speed_dataset2[speed_dataset2['DAY']==ii+1]
    for jj in range(num_interval):
        #print(jj)
        AA=speed_dataset[speed_dataset['Interval_10']==jj]
        speed_value_ingrid=np.zeros(729)
        for k in range(s,s+len(AA)):
            speed_value_ingrid[AA['grid_id'][k]]=AA['risk_level'][k]+speed_value_ingrid[AA['grid_id'][k]]
            kk=kk+1
        speed_halfhour[ii,jj,:]=speed_value_ingrid
        s=kk
        #print(s)

In [210]:
index_road=pd.DataFrame(pd.read_csv("E:/data ming/accident_prediction/NYC_data/Experimental_data/index_road.csv"))
index_road=np.array(index_road)
index_road=np.array(index_road)[:,0]
# def transfer_729(A):
#     B1=np.zeros([729])
    
#     for i in range(354):
#         B1[index_road[i]]=A[i]
#     B1=B1.reshape([27,27])
#     return B1
#转换成354

def transfer_354(A):
    B1=np.zeros([354])
    A=np.array(A).reshape([729])
    for i in range(354):
        B1[i]=A[index_road[i]]
    return B1
Conv_1=np.zeros([day_num,num_interval,27,27])
Graph_region=np.zeros([day_num,num_interval,354])
for i in range(day_num):
    for j in range(num_interval):
        Conv_1[i,j,:,:]=speed_halfhour[i,j,:].reshape([27,27])
        Graph_region[i,j,:]=transfer_354(speed_halfhour[i,j,:])

In [211]:
Conv_2= np.zeros([Total_interval,27,27])
Graph_2=np.zeros([354,Total_interval])
for i in range(0,day_num):
    for j in range(0,num_interval):
        Conv_2[i*num_interval+j,:,:]=Conv_1[i,j,:,:]
        Graph_2[:,i*num_interval+j]=Graph_region[i,j,:]

In [212]:
np.save(r'E:\data ming\accident_prediction\NYC_data\Experimental_data\Acc_speed_taxi_01_finegrained\Acc_'+'%02d'%month_num+'_graph10in.npy',Graph_2)
np.save(r'E:\data ming\accident_prediction\NYC_data\Experimental_data\Acc_speed_taxi_01_finegrained\Acc_'+'%02d'%month_num+'_conv10in.npy',Conv_2)

In [276]:
A1 = np.zeros([291,1])
A2 = np.ones([310,1])
A = np.concatenate([A1,A2])
A= list(A)
random.shuffle(A)

In [278]:
np.save('random_601.npy',A)

In [279]:
sum(A)

array([310.])

In [263]:
import numpy as np
import pandas as pd
import collections

taxi_data01=pd.read_csv(r'E:\data ming\accident_prediction\NYC_data\taxi_1701.csv')

In [269]:
taxi_data = taxi_data.drop(columns=['store_and_fwd_flag','tolls_amount','payment_type','improvement_surcharge','tip_amount','extra','fare_amount'])

In [283]:
taxi_data01['pick_time'].max()

1439.0

In [268]:
taxi_data=pd.read_csv(r'E:\data ming\accident_prediction\NYC_data\taxi_data\yellow_tripdata_2017-02.csv')

In [271]:
taxi_data['Month']=0
taxi_data['Day']=0
taxi_data['min1']=0
taxi_data['min2']=0
taxi_data['Month'] = pd.to_datetime(taxi_data['tpep_pickup_datetime']).month

AttributeError: 'Series' object has no attribute 'month'

In [280]:
taxi_data

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,mta_tax,total_amount
0,2,2017/2/3 2:03,2017/2/3 2:20,1,3.29,1,87,246,0.5,16.30
1,2,2017/2/3 2:26,2017/2/3 2:46,1,2.80,1,68,239,0.5,15.80
2,2,2017/2/3 2:49,2017/2/3 9:56,1,0.90,1,239,43,0.5,8.16
3,2,2017/2/3 4:41,2017/2/3 4:52,1,0.72,1,163,230,0.5,10.56
4,2,2017/2/3 4:57,2017/2/3 12:16,1,1.10,1,186,230,0.5,15.34
5,2,2017/2/21 14:50,2017/2/21 15:03,1,0.93,1,141,162,0.5,9.80
6,2,2017/2/21 23:23,2017/2/21 23:26,6,0.84,1,234,68,0.5,7.18
7,2,2017/2/21 23:28,2017/2/21 23:39,6,2.01,1,249,161,0.5,14.12
8,2,2017/2/21 23:55,2017/2/22 0:01,6,1.52,1,144,87,0.5,10.38
9,2,2017/2/24 12:17,2017/2/24 12:28,1,1.01,1,230,68,0.5,11.44
10,2,2017/2/24 12:29,2017/2/24 12:33,1,0.72,1,68,68,0.5,6.89
11,2,2017/2/24 12:47,2017/2/24 12:59,1,1.60,1,231,113,0.5,11.76
12,2,2017/2/24 13:03,2017/2/24 22:04,1,4.31,1,113,239,0.5,38.30
13,1,2017/2/1 0:00,2017/2/1 0:20,1,10.30,1,138,162,0.5,37.34
14,2,2017/2/1 0:00,2017/2/1 0:24,1,16.05,1,132,123,0.5,45.30
15,1,2017/2/1 0:00,2017/2/1 0:14,1,2.40,1,148,68,0.5,16.30
16,1,2017/2/1 0:00,2017/2/1 0:21,1,10.40,1,137,213,0.5,38.15
17,2,2017/2/1 0:00,2017/2/1 0:05,4,0.76,1,170,170,0.5,8.16
18,2,2017/2/1 0:00,2017/2/1 0:10,2,2.80,1,230,79,0.5,14.16
19,2,2017/2/1 0:00,2017/2/1 0:07,1,2.48,1,142,246,0.5,10.80
20,2,2017/2/1 0:00,2017/2/1 0:29,1,13.60,1,138,13,0.5,45.30
21,2,2017/2/1 0:00,2017/2/1 0:03,1,0.76,1,263,75,0.5,7.88
22,2,2017/2/1 0:00,2017/2/1 0:07,1,1.30,1,162,100,0.5,8.80
23,2,2017/2/1 0:00,2017/2/1 0:04,1,1.28,1,48,239,0.5,9.50
24,1,2017/2/1 0:00,2017/2/1 0:33,2,9.30,1,249,244,0.5,31.80
25,1,2017/2/1 0:00,2017/2/1 0:10,1,3.20,1,144,229,0.5,12.80
26,1,2017/2/1 0:00,2017/2/1 0:19,1,9.10,1,138,78,0.5,34.84
27,2,2017/2/1 0:00,2017/2/1 0:07,1,1.41,1,163,239,0.5,10.00
28,2,2017/2/1 0:00,2017/2/1 0:12,1,4.07,1,87,25,0.5,19.12
29,1,2017/2/1 0:00,2017/2/1 0:06,1,0.80,1,107,90,0.5,7.30
...,...,...,...,...,...,...,...,...,...,...
1048544,2,2017/2/3 23:26,2017/2/3 23:42,1,3.37,1,234,143,0.5,16.80
1048545,1,2017/2/3 23:26,2017/2/3 23:33,1,1.50,1,125,87,0.5,9.95
1048546,1,2017/2/3 23:26,2017/2/3 23:33,1,1.70,1,264,264,0.5,9.30
1048547,1,2017/2/3 23:26,2017/2/3 23:39,1,2.60,1,142,262,0.5,15.95
1048548,2,2017/2/3 23:26,2017/2/3 23:57,1,7.36,1,107,189,0.5,32.00
1048549,1,2017/2/3 23:26,2017/2/3 23:38,2,2.60,1,238,237,0.5,15.35
1048550,1,2017/2/3 23:26,2017/2/3 23:33,1,0.50,1,264,264,0.5,9.45
1048551,1,2017/2/3 23:26,2017/2/3 23:30,1,0.70,1,141,229,0.5,7.55
1048552,1,2017/2/3 23:26,2017/2/3 23:44,1,3.00,1,231,170,0.5,18.35
1048553,2,2017/2/3 23:26,2017/2/3 23:48,1,4.13,1,263,234,0.5,21.96
1048554,2,2017/2/3 23:26,2017/2/3 23:35,2,1.25,1,182,78,0.5,8.80
1048555,1,2017/2/3 23:26,2017/2/3 23:48,1,9.80,1,138,36,0.5,40.80
1048556,1,2017/2/3 23:26,2017/2/3 23:53,3,3.40,1,163,107,0.5,24.10
1048557,1,2017/2/3 23:26,2017/2/3 23:47,1,3.50,1,249,97,0.5,20.75
1048558,1,2017/2/3 23:26,2017/2/3 23:38,1,1.30,1,79,107,0.5,10.30
1048559,1,2017/2/3 23:26,2017/2/3 23:30,1,0.90,1,113,68,0.5,8.50
1048560,2,2017/2/3 23:26,2017/2/3 23:34,2,0.52,1,79,148,0.5,7.80
1048561,2,2017/2/3 23:26,2017/2/3 23:35,4,2.01,1,68,170,0.5,9.80
1048562,2,2017/2/3 23:26,2017/2/3 23:56,1,3.24,1,79,164,0.5,20.30
1048563,2,2017/2/3 23:26,2017/2/3 23:44,1,11.13,1,132,82,0.5,39.75
1048564,2,2017/2/3 23:26,2017/2/3 23:43,1,3.50,1,49,157,0.5,16.30
1048565,2,2017/2/3 23:26,2017/2/3 23:50,1,11.84,1,233,58,0.5,34.80
1048566,1,2017/2/3 23:26,2017/2/3 23:35,1,1.60,1,239,237,0.5,11.75
1048567,1,2017/2/3 23:26,2017/2/3 23:34,2,1.00,1,144,79,0.5,8.80
1048568,1,2017/2/3 23:26,2017/2/3 23:46,1,3.70,1,114,142,0.5,19.80
1048569,2,2017/2/3 23:26,2017/2/3 23:38,1,1.65,1,234,79,0.5,12.96
1048570,2,2017/2/3 23:26,2017/2/3 23:36,1,1.73,1,97,17,0.5,11.76
1048571,2,2017/2/3 23:26,2017/2/3 23:32,1,0.88,1,50,143,0.5,7.30
1048572,2,2017/2/3 23:26,2017/2/3 23:49,1,4.22,1,50,148,0.5,24.75
1048573,2,2017/2/3 23:26,2017/2/3 23:34,1,1.85,1,142,238,0.5,9.80

In [260]:
import datetime
pd.to_datetime(taxi_data.iloc[0]['tpep_pickup_datetime']).day

3

In [262]:
taxi_data.iloc[0]['tpep_pickup_datetime']

'2017-02-03 02:03:50'

In [261]:
pd.to_datetime(taxi_data.iloc[0]['tpep_pickup_datetime']).hour
pd.to_datetime(taxi_data.iloc[0]['tpep_pickup_datetime']).minute

3

In [ ]:
pd.to_datetime(taxi_data.iloc[0]['tpep_pickup_datetime']).day

In [157]:
#对一个月的数据做处理 每天30min一个interval 一天48个 31*48
Interval=10 #10分钟
day_num=31
num_interval=np.int(1440/Interval) #一天里多少interval
Total_interval=day_num*num_interval
taxi_halfhour_pick= np.zeros([day_num,num_interval,27,27])#生成数组保存每组速度
taxi_halfhour_drop= np.zeros([day_num,num_interval,27,27])#
ss=np.int32(0)
for ii in range(0,day_num):
    taxi_dataset=taxi_data[taxi_data['Day']==ii+1]
    count_half_hour=np.zeros(num_interval+1)  #生成数组保存每组的个数，每半小时一个为48 下面为30分钟 27*27是网格大小
    for j in range(0,num_interval):# 分段，计算每个interval中有几条记录 然后每次索引时用这个数据来控制归类的数据条目段
        ab=np.where((taxi_dataset['pick_time']>=Interval*j)&(taxi_dataset['pick_time']<Interval*j+Interval),1,0)
        count_half_hour[j+1]=collections.Counter(ab)[1]
    for j in range(0,num_interval):
        #speed_value_ingrid=np.zeros(729)
        count_pick_id=np.zeros(729)
        count_drop_id=np.zeros(729)
        for i in range(ss,ss+np.int32(count_half_hour[j+1])):
            #print(ii,i,j)
            count_pick_id[np.int(taxi_dataset['pick_ID'][i])]=count_pick_id[np.int(taxi_dataset['pick_ID'][i])]+1
            count_drop_id[np.int(taxi_dataset['drop_ID'][i])]=count_drop_id[np.int(taxi_dataset['drop_ID'][i])]+1
        ss=np.int32(ss)+np.int32(count_half_hour[j+1])#ss为总的累计值
        #print(ss)
        
        taxi_halfhour_pick[ii,j,:,:]=count_pick_id.reshape(27,27)
        taxi_halfhour_drop[ii,j,:,:]=count_drop_id.reshape(27,27)
    print(ss)

#映射到三维当中去
taxi_halfhour_pick1= np.zeros([Total_interval,27,27])
taxi_halfhour_drop1= np.zeros([Total_interval,27,27])
for i in range(0,day_num):
    for j in range(0,num_interval):
        taxi_halfhour_pick1[i*num_interval+j,:,:]=taxi_halfhour_pick[i,j,:,:]
        taxi_halfhour_drop1[i*num_interval+j,:,:]=taxi_halfhour_drop[i,j,:,:]
taxi_pick_10in=np.zeros([354,Total_interval])
taxi_drop_10in=np.zeros([354,Total_interval])

for i in range(Total_interval):
    taxi_pick_10in[:,i]=transfer_354(taxi_halfhour_pick1[i,:,:])
    taxi_drop_10in[:,i]=transfer_354(taxi_halfhour_drop1[i,:,:])

281088
281139
281139
281139
281139
281139
281139
281140
281162
281163
281186
281202
281215
398967
706346
826420
1039617
1039617
1039617
1039617
1039617
1048568
1048568
1048568
1048568
1048568
1048568
1048568
1048568
1048569
1048574

In [172]:
taxi_pick_10in[0,:]=0
taxi_drop_10in[0,:]=0
taxi_halfhour_pick1[:,0,0]=0
taxi_halfhour_drop1[:,0,0]=0

In [136]:
taxi_dataset['pick_ID']

4         356
5         383
6         383
7         331
8         383
9         383
10        283
11        383
12        304
13        383
14        383
15        358
16        385
17        383
18        304
19        383
20        383
21        198
22        383
23        283
24        383
25        383
26        330
27        383
28        383
29        545
30        383
31        383
32        383
33        283
         ...
706697    530
706698    383
706699    383
706700    383
706701    283
706702    303
706703    383
706704    286
706705    383
706706    385
706707    251
706708    383
706709      0
706710    384
706711    383
706712    304
706713    383
706714    331
706715    383
706716    356
706717    330
706718    358
706719    383
706720    383
706772    411
706773    303
706774    383
706775    383
706776    383
706777      0
Name: pick_ID, Length: 281088, dtype: int64

In [173]:
np.save(r'E:\data ming\accident_prediction\NYC_data\Experimental_data\Acc_speed_taxi_01_finegrained\taxi_pick_graph_10in.npy',taxi_pick_10in)
np.save(r'E:\data ming\accident_prediction\NYC_data\Experimental_data\Acc_speed_taxi_01_finegrained\taxi_drop_graph_10in.npy',taxi_drop_10in)
#np.save(r'E:\data ming\accident_prediction\NYC_data\Experimental_data\Acc_speed_taxi_01_finegrained\taxi_pick_conv_10in.npy',taxi_halfhour_pick1)
#np.save(r'E:\data ming\accident_prediction\NYC_data\Experimental_data\Acc_speed_taxi_01_finegrained\taxi_drop_conv_10in.npy',taxi_halfhour_drop1)

In [152]:
for i in range(1000):
    print(sum(taxi_pick_10in[:,i]))

43.0
0.0
1.0
1.0
2.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0

In [166]:
sum(taxi_pick_10in[:,10])

3690.0

In [167]:
sum(taxi_drop_10in[:,10])

3668.0

In [170]:
np.int32(taxi_halfhour_pick[0,17,:,:])

array([[  86,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1,
           2,    0,    1,    0,    1,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    5,
           0,    1,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    4,    2,
           1,    1,    0,    1,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,   15,    1,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,   20,    0,    1,
           1,    0,    0,    2,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,   20,   39,    2,
           0,    1,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,   20,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,   25,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,   45,
           0,    0,    3,    0,    1,  137,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,   43,   27,   97,   78,   13,    0,
           0,    9,    5,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,  133,  234,    0,   18,   13,
          10,    6,    1,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,   67,   50,  234,    0,   15,    0,
           4,    0,    3,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0, 1530,   47,  119,    0,    0,    0,
           0,    1,    0,    1,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    1,    8,    4,    0,   18,    0,
           5,    0,    0,    0,    1,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    3,   21,    3,    9,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,   14,   27,    7,    0,    0,
           0,    0,    0,    1,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           1,    1,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    4,    0,    0,
           0,    0,    0,    0,    0,    0,   12,    0,    0,    0,    0,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    1,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    1,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0]])