In [1]:
import numpy as np
import pandas as pd
month_num = 5
taxi_trip=pd.read_csv(r'E:\data ming\accident_prediction\NYC_data\taxi_data\yellow_tripdata_2017-'+'%02d'%month_num+'.csv')

In [2]:
Month_day = [31,28,31,30,31,30,31,31,30,31,30,31]
taxi_trip = taxi_trip.drop(columns=['store_and_fwd_flag','tolls_amount','payment_type','improvement_surcharge','tip_amount','extra','fare_amount'])
path="E:/data ming/accident_prediction/NYC_data/taxi_data/taxi_loca11.csv"
all_data=pd.DataFrame(pd.read_csv(path))
index_num=np.zeros([266,2]) #建立空矩阵 存放索引号-索引内容
index_num[all_data['LocationID'],0]=all_data['LocationID'] #填充索引内容
index_num[all_data['LocationID'],1]=all_data['grid_id'] #填充索引内容

In [3]:
len(taxi_trip)

10102124

In [4]:
#path="E:/data ming/accident_prediction/NYC_data/taxi_data/yellow_tripdata_2017-01.csv"
taxi_data=taxi_trip
#索引成功后的数组
PULocationGrid_ID=[]
DOLocationGrid_ID=[]
Month1 = []
Day1 = []
Min1 = []
Min2 = []
Pick_time = []
Drop_time = []


    
    
for i in range(0,len(taxi_data)):
    PULocationGrid_ID.append(index_num[taxi_data['PULocationID'][i],1])
    DOLocationGrid_ID.append(index_num[taxi_data['DOLocationID'][i],1])
    
    datatime0 = pd.to_datetime(taxi_data['tpep_pickup_datetime'][i])
    datatime1 = pd.to_datetime(taxi_data['tpep_dropoff_datetime'][i])
    
    pick_time = datatime0.hour*60+datatime0.minute
    Pick_time.append(pick_time)

    drop_time = datatime1.hour*60+datatime1.minute
    Drop_time.append(drop_time)
   
    Month1.append(datatime0.month)
    Day1.append(datatime0.day)
    
    Min1.append(pick_time/1440)
    Min2.append(drop_time/1440)
    
#保存为原矩阵中的内容，增加两列。
taxi_data['pick_ID']=PULocationGrid_ID  
taxi_data['drop_ID']=DOLocationGrid_ID 
taxi_data['Month']=Month1
taxi_data['Day']=Day1
taxi_data['min1']=Min1
taxi_data['min2']=Min2
taxi_data['pick_time']=Pick_time
taxi_data['drop_time']=Drop_time
#将结果输出

In [5]:
taxi_data = taxi_data.sort_values(['Day','pick_time'],ascending= [True,True])
pd.DataFrame(taxi_data).to_csv('E:/data ming/accident_prediction/NYC_data/taxi_17'+'%02d'%month_num+'.csv')#直接输出网格index
taxi_data=pd.DataFrame(pd.read_csv('E:/data ming/accident_prediction/NYC_data/taxi_17'+'%02d'%month_num+'.csv'))
day_num= Month_day[month_num-1]
Interval=10 #10分钟
num_interval=np.int(1440/Interval)

In [19]:
np.unique(taxi_data['Day'])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30], dtype=int64)

In [6]:
#对一个月的数据做处理 每天30min一个interval 一天48个 31*48
import collections
taxi_halfhour_pick= np.zeros([day_num,num_interval,27,27])#生成数组保存每组速度
taxi_halfhour_drop= np.zeros([day_num,num_interval,27,27])#
ss=np.int32(0)
for ii in range(1,day_num+1):
    taxi_dataset=taxi_data[taxi_data['Day']==np.float(ii)]
    count_half_hour=np.zeros(num_interval+1)  #生成数组保存每组的个数，每半小时一个为48 下面为30分钟 27*27是网格大小
    for j in range(0,num_interval):# 分段，计算每个interval中有几条记录 然后每次索引时用这个数据来控制归类的数据条目段
        ab=np.where((taxi_dataset['pick_time']>=Interval*j)&(taxi_dataset['pick_time']<Interval*j+Interval),1,0)
        count_half_hour[j+1]=collections.Counter(ab)[1]
    for j in range(0,num_interval):
        #speed_value_ingrid=np.zeros(729)
        count_pick_id=np.zeros(729)
        count_drop_id=np.zeros(729)
        for i in range(ss,ss+np.int32(count_half_hour[j+1])):
            #print(ii,i,j)
            count_pick_id[np.int(taxi_dataset['pick_ID'][i])]=count_pick_id[np.int(taxi_dataset['pick_ID'][i])]+1
            count_drop_id[np.int(taxi_dataset['drop_ID'][i])]=count_pick_id[np.int(taxi_dataset['drop_ID'][i])]+1
        ss=np.int32(ss)+np.int32(count_half_hour[j+1])#ss为总的累计值
        #print(ss)
       
        taxi_halfhour_pick[ii-1,j,:,:]=count_pick_id.reshape(27,27)
        taxi_halfhour_drop[ii-1,j,:,:]=count_drop_id.reshape(27,27)
    print(ss)

#映射到三维当中去
taxi_halfhour_pick1= np.zeros([day_num*num_interval,27,27])
taxi_halfhour_drop1= np.zeros([day_num*num_interval,27,27])
for i in range(0,day_num):
    for j in range(0,num_interval):
        taxi_halfhour_pick1[i*num_interval+j,:,:]=taxi_halfhour_pick[i,j,:,:]
        taxi_halfhour_drop1[i*num_interval+j,:,:]=taxi_halfhour_drop[i,j,:,:]

303360
635926
981948
1337525
1700307
2070806
2388833
2695812
3026291
3366660
3714906
4068998
4440148
4737221
5049665
5386883
5738959
6088147
6452433
6820098
7139505
7446814
7770448
8107026
8449471
8755528
9022933
9264343
9477697
9774335
10102124

In [8]:
taxi_halfhour_pick1= np.zeros([day_num*num_interval,27,27])
taxi_halfhour_drop1= np.zeros([day_num*num_interval,27,27])
for i in range(0,day_num):
    for j in range(0,num_interval):
        taxi_halfhour_pick1[i*num_interval+j,:,:]=taxi_halfhour_pick[i,j,:,:]
        taxi_halfhour_drop1[i*num_interval+j,:,:]=taxi_halfhour_drop[i,j,:,:]
for i in range(day_num*num_interval):
    taxi_halfhour_pick1[i,0,0]=0
    taxi_halfhour_drop1[i,0,0]=0
index_road=pd.DataFrame(pd.read_csv("E:/data ming/accident_prediction/NYC_data/Experimental_data/index_road.csv"))
index_road=np.array(index_road)[:,0]
def transfer_354(A):
    B1=np.zeros([354])
    A=np.array(A).reshape([729])
    for i in range(354):
        B1[i]=A[index_road[i]]
    return B1
taxi_halfhour_pick1_04=np.zeros([354,day_num*num_interval])
taxi_halfhour_drop1_04=np.zeros([354,day_num*num_interval])
for i in range(day_num*num_interval):
    taxi_halfhour_pick1_04[:,i]=transfer_354(taxi_halfhour_pick1[i,:,:])
    taxi_halfhour_drop1_04[:,i]=transfer_354(taxi_halfhour_drop1[i,:,:])
np.save('taxi_halfhour_pick_'+'%02d'%month_num+'.npy',taxi_halfhour_pick1_04)
np.save('taxi_halfhour_drop_'+'%02d'%month_num+'.npy',taxi_halfhour_drop1_04)

In [34]:
Taxi_trip_04=np.load(r'E:\data ming\accident_prediction\NYC_data\Experimental_data\taxi_pick_drop\taxi_pick_2017_04.npy')

In [31]:
taxi_halfhour_pick1[0,10,10]

29.0

In [37]:
Taxi_trip_04.shape

(354, 720)

In [103]:
month_num

3

In [53]:
sum(taxi_halfhour_pick1_04[:,0])+sum(taxi_halfhour_pick1_04[:,1])

17170.0

In [65]:
sum(Taxi_trip_04[:,-1])

8666.0

In [120]:
import numpy as np
import pandas as pd
taxi_trip_05=pd.read_csv(r'E:\data ming\accident_prediction\NYC_data\taxi_data\yellow_tripdata_2017-05.csv')
path="E:/data ming/accident_prediction/NYC_data/taxi_data/taxi_loca11.csv"
all_data=pd.DataFrame(pd.read_csv(path))
index_num=np.zeros([266,2]) #建立空矩阵 存放索引号-索引内容
index_num[all_data['LocationID'],0]=all_data['LocationID'] #填充索引内容
index_num[all_data['LocationID'],1]=all_data['grid_id'] #填充索引内容

#path="E:/data ming/accident_prediction/NYC_data/taxi_data/yellow_tripdata_2017-01.csv"
taxi_data=taxi_trip_05
#索引成功后的数组
PULocationGrid_ID=[]
DOLocationGrid_ID=[]
for i in range(0,len(taxi_data)):
    PULocationGrid_ID.append(index_num[taxi_data['PULocationID'][i],1])
    DOLocationGrid_ID.append(index_num[taxi_data['DOLocationID'][i],1])
#保存为原矩阵中的内容，增加两列。
taxi_data['PULocationGrid_ID']=PULocationGrid_ID  
taxi_data['DOLocationGrid_ID']=DOLocationGrid_ID  
#将结果输出
pd.DataFrame(taxi_data).to_csv('E:/data ming/accident_prediction/NYC_data/taxi_1705.csv')#直接输出网格index

In [121]:
taxi_trip_05=pd.read_csv(r'E:\data ming\accident_prediction\NYC_data\taxi_1705.csv')

In [122]:
taxi_trip_05

,Unnamed: 0,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,PULocationGrid_ID,DOLocationGrid_ID
0,0,2,2017-05-18 00:36:42,2017-05-18 00:38:41,6,0.43,1,N,236,236,2,3.5,1.0,0.5,0.00,0.00,0.3,5.30,383.0,383.0
1,1,1,2017-05-01 00:00:00,2017-05-01 00:25:18,1,17.10,2,N,132,141,1,52.0,0.0,0.5,10.55,0.00,0.3,63.35,530.0,383.0
2,2,1,2017-05-01 00:00:00,2017-05-01 00:22:42,1,9.90,1,N,138,50,1,29.0,0.5,0.5,7.20,5.76,0.3,43.26,283.0,383.0
3,3,2,2017-05-01 00:00:00,2017-05-01 00:27:42,1,4.40,1,N,48,7,2,19.5,0.5,0.5,0.00,0.00,0.3,20.80,383.0,280.0
4,4,2,2017-05-01 00:00:00,2017-05-01 00:00:00,1,1.81,1,N,186,233,2,18.0,0.0,0.5,0.00,0.00,0.3,18.80,383.0,383.0
5,5,2,2017-05-01 00:00:00,2017-05-01 15:38:37,2,0.00,5,N,264,142,1,60.0,0.0,0.0,0.00,0.00,0.0,60.00,0.0,383.0
6,6,1,2017-05-01 00:00:01,2017-05-01 00:16:31,1,3.60,1,N,211,161,2,15.0,0.5,0.5,0.00,0.00,0.3,16.30,356.0,304.0
7,7,1,2017-05-01 00:00:01,2017-05-01 00:09:58,1,1.80,1,N,48,229,2,9.0,0.5,0.5,0.00,0.00,0.3,10.30,383.0,305.0
8,8,1,2017-05-01 00:00:02,2017-05-01 00:18:49,1,4.10,1,N,142,144,2,16.0,0.5,0.5,0.00,0.00,0.3,17.30,383.0,357.0
9,9,2,2017-05-17 23:49:35,2017-05-17 23:54:34,6,0.85,1,N,170,163,2,5.5,1.0,0.5,0.00,0.00,0.3,7.30,286.0,383.0
10,10,2,2017-05-17 23:56:05,2017-05-18 00:06:33,6,0.67,1,N,163,163,2,7.5,1.0,0.5,0.00,0.00,0.3,9.30,383.0,383.0
11,11,2,2017-05-18 00:19:45,2017-05-18 00:31:18,6,1.78,1,N,163,236,1,9.5,1.0,0.5,2.26,0.00,0.3,13.56,383.0,383.0
12,12,2,2017-05-01 00:00:02,2017-05-01 00:11:40,2,2.52,1,N,230,158,2,10.5,0.5,0.5,0.00,0.00,0.3,11.80,304.0,383.0
13,13,1,2017-05-01 00:00:03,2017-05-01 00:04:23,2,0.70,1,N,232,148,1,5.0,0.5,0.5,1.25,0.00,0.3,7.55,384.0,385.0
14,14,2,2017-05-01 00:00:03,2017-05-01 00:17:01,5,8.41,1,N,138,233,1,24.5,0.5,0.5,4.00,5.76,0.3,35.56,283.0,383.0
15,15,2,2017-05-01 00:00:03,2017-05-01 00:11:56,1,2.91,1,N,100,144,1,11.0,0.5,0.5,2.46,0.00,0.3,14.76,303.0,357.0
16,16,1,2017-05-01 00:00:05,2017-05-01 00:03:01,1,0.30,1,N,144,231,2,4.0,0.5,0.5,0.00,0.00,0.3,5.30,357.0,383.0
17,17,2,2017-05-01 00:00:05,2017-05-01 00:16:09,2,3.64,1,N,90,43,1,14.5,0.5,0.5,3.16,0.00,0.3,18.96,330.0,251.0
18,18,1,2017-05-01 00:00:06,2017-05-01 00:10:30,3,3.30,1,N,138,179,2,12.5,0.5,0.5,0.00,0.00,0.3,13.80,283.0,280.0
19,19,2,2017-05-01 00:00:06,2017-05-01 00:01:47,1,0.18,1,N,148,148,2,3.0,0.5,0.5,0.00,0.00,0.3,4.30,385.0,385.0
20,20,2,2017-05-01 00:00:07,2017-05-01 00:08:58,1,2.52,1,N,68,162,2,10.0,0.5,0.5,0.00,0.00,0.3,11.30,330.0,331.0
21,21,2,2017-05-01 00:00:07,2017-05-01 00:15:48,3,2.31,1,N,79,158,1,12.0,0.5,0.5,3.32,0.00,0.3,16.62,358.0,383.0
22,22,1,2017-05-01 00:00:08,2017-05-01 00:28:13,1,12.00,1,N,162,173,3,36.0,0.5,0.5,0.00,5.76,0.3,43.06,331.0,310.0
23,23,1,2017-05-01 00:00:08,2017-05-01 00:07:44,2,1.30,1,N,49,97,2,7.5,0.5,0.5,0.00,0.00,0.3,8.80,440.0,439.0
24,24,2,2017-05-01 00:00:08,2017-05-01 00:09:29,1,2.36,1,N,163,236,1,9.5,0.5,0.5,2.16,0.00,0.3,12.96,383.0,383.0
25,25,1,2017-05-01 00:00:10,2017-05-01 00:13:54,2,3.40,1,N,162,114,1,12.5,0.5,0.5,2.00,0.00,0.3,15.80,331.0,383.0
26,26,1,2017-05-01 00:00:10,2017-05-01 00:02:20,1,0.40,1,N,116,42,1,4.0,0.5,0.5,1.30,0.00,0.3,6.60,170.0,383.0
27,27,1,2017-05-01 00:00:10,2017-05-01 00:12:51,1,2.50,1,N,68,79,1,11.5,0.5,0.5,2.55,0.00,0.3,15.35,330.0,358.0
28,28,2,2017-05-01 00:00:10,2017-05-01 00:14:23,5,7.64,1,N,48,244,1,23.0,0.5,0.5,0.00,0.00,0.3,24.30,383.0,144.0
29,29,1,2017-05-01 00:00:11,2017-05-01 00:05:43,1,1.50,1,N,100,90,2,7.0,0.5,0.5,0.00,0.00,0.3,8.30,303.0,330.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10102094,10102094,2,2017-05-31 23:59:52,2017-06-01 00:01:56,1,0.48,1,N,100,230,2,4.0,0.5,0.5,0.00,0.00,0.3,5.30,303.0,304.0
10102095,10102095,2,2017-05-31 23:59:52,2017-06-01 00:02:40,1,1.09,1,N,238,239,1,5.0,0.5,0.5,1.26,0.00,0.3,7.56,383.0,383.0
10102096,10102096,2,2017-05-31 23:59:52,2017-06-01 00:03:43,1,0.74,1,N,107,164,1,5.0,0.5,0.5,1.26,0.00,0.3,7.56,331.0,383.0
10102097,10102097,2,2017-05-31 23:59:52,2017-06-01 00:16:46,2,4.16,1,N,231,233,1,15.0,0.5,0.5,3.26,0.00,0.3,19.56,383.0,383.0
10102098,10102098,2,2017-05-31 23:59:53,2017-06-01 00:08:22,2,2.01,1,N,234,161,2,9.0,0.5,0.5,0.00,0.00,0.3,10.30,383.0,304.0
10102099,10102099,2,2017-05-31 23:59:53,2017-06-01 00:15:28,5,2.97,1,N,148,25,1,12.5,0.5,0.5,2.00,0.00,0.3,15.80,385.0,439.0
10102100,10102100,1,2017-05-31 23:59:54,2017-06-01 00:19:25,1,5.40,1,N,233,209,2,19.0,0.5,0.5,0.00,0.00,0.3,20.30,383.0,383.0
10102101,10102101,1,2017-05-31 23:59:54,2017-06-01 00:11:44,1,2.50,1,N,144,256,1,11.5,0.5,0.5,2.55,0.00,0.3,15.35,357.0,383.0
10102102,10102102,2,2017-05-31 23:59:54,2017-06-01 00:02:28,1,0.68,1,N,234,113,1,4.5,0.5,0.5,1.16,0.00,0.3,6.96,383.0,383.0
10102103,10102103,2,2017-05-31 23:59:54,2017-06-01 00:21:37,1,5.62,1,N,114,143,2,20.5,0.5,0.5,0.00,0.00,0.3,21.80,383.0,383.0
10102104,10102104,2,2017-05-31 23:59:54,2017-06-01 00:02:40,4,0.36,1,N,4,79,2,3.5,0.5,0.5,0.00,0.00,0.3,4.80,358.0,358.0
10102105,10102105,2,2017-05-31 23:59:54,2017-06-01 00:09:32,2,1.53,1,N,246,164,2,8.5,0.5,0.5,0.00,0.00,0.3,9.80,302.0,383.0
10102106,10102106,2,2017-05-31 23:59:54,2017-06-01 00:20:37,1,15.28,1,N,132,179,1,41.0,0.5,0.5,8.46,0.00,0.3,50.76,530.0,280.0
10102107,10102107,1,2017-05-31 23:59:55,2017-06-01 00:21:07,1,9.10,1,N,230,40,1,27.5,0.5,0.5,2.00,5.76,0.3,36.56,304.0,465.0
10102108,10102108,1,2017-05-31 23:59:55,2017-06-01 00:11:53,1,2.50,1,N,186,148,2,10.5,0.5,0.5,0.00,0.00,0.3,11.80,383.0,385.0
10102109,10102109,2,2017-05-31 23:59:55,2017-06-01 00:14:08,1,2.30,1,N,177,61,1,11.5,0.5,0.5,10.00,0.00,0.3,22.80,470.0,383.0
10102110,10102110,1,2017-05-31 23:59:56,2017-06-01 00:06:43,1,1.20,1,N,164,233,1,6.5,0.5,0.5,2.00,0.00,0.3,9.80,383.0,383.0
10102111,10102111,2,2017-05-31 23:59:57,2017-06-01 00:17:17,1,2.74,1,N,164,211,1,13.5,0.5,0.5,4.00,0.00,0.3,18.80,383.0,356.0
10102112,10102112,2,2017-05-31 23:59:57,2017-06-01 00:06:23,2,2.21,1,N,239,41,1,8.5,0.5,0.5,2.45,0.00,0.3,12.25,383.0,198.0
10102113,10102113,2,2017-05-31 23:59:57,2017-06-01 00:12:06,3,3.86,1,N,234,75,1,13.5,0.5,0.5,2.96,0.00,0.3,17.76,383.0,383.0
10102114,10102114,2,2017-05-31 23:59:57,2017-06-01 00:31:31,1,18.00,2,N,132,163,1,52.0,0.0,0.5,9.00,5.76,0.3,67.56,530.0,383.0
10102115,10102115,1,2017-05-31 23:59:58,2017-06-01 00:22:56,1,8.00,1,N,239,209,1,26.0,0.5,0.5,2.00,0.00,0.3,29.30,383.0,383.0
10102116,10102116,2,2017-05-31 23:59:58,2017-06-01 00:20:18,1,4.65,1,N,231,141,1,17.5,0.5,0.5,3.76,0.00,0.3,22.56,383.0,383.0
10102117,10102117,2,2017-05-31 23:59:58,2017-06-01 00:14:52,1,5.80,1,N,261,162,1,19.0,0.5,0.5,2.00,0.00,0.3,22.30,383.0,331.0
10102118,10102118,1,2017-05-31 23:59:59,2017-06-01 00:30:41,1,14.10,1,N,138,144,1,42.5,0.5,0.5,9.90,5.76,0.3,59.46,283.0,357.0
10102119,10102119,1,2017-05-31 23:59:59,2017-06-01 00:05:55,1,1.20,1,N,264,264,1,6.5,0.5,0.5,1.95,0.00,0.3,9.75,0.0,0.0
10102120,10102120,2,2017-05-31 23:59:59,2017-06-01 00:16:30,1,4.40,1,N,114,140,1,15.0,0.5,0.5,2.00,0.00,0.3,18.30,383.0,383.0
10102121,10102121,1,2017-05-03 00:31:22,2017-05-03 00:40:14,1,1.60,1,N,246,113,1,8.0,0.5,0.5,1.00,0.00,0.3,10.30,302.0,383.0
10102122,10102122,1,2017-05-03 00:53:31,2017-05-03 00:58:04,1,1.00,1,N,68,246,1,5.5,0.5,0.5,0.00,0.00,0.3,6.80,330.0,302.0
10102123,10102123,1,2017-05-03 01:02:23,2017-05-03 01:16:37,1,1.80,1,N,246,237,2,10.5,0.5,0.5,0.00,0.00,0.3,11.80,302.0,383.0

In [ ]:
for i in range(len(taxi_trip_05)):
    current=taxi_trip_05['tpep_pickup_datetime'][i]
    current_time= datetime.datetime.strptime(current,"%Y-%m-%d %H:%M:%S")
    Day=cuurent_time.day
    Hour=cuurent_time.min

In [127]:
import collections
import math
taxi_halfhour_pick= np.zeros([31,48,729])#生成数组保存每组速度
taxi_halfhour_drop= np.zeros([31,48,729])#
for i in range(len(taxi_trip_05)):
    current=taxi_trip_05['tpep_pickup_datetime'][i]
    #print(current)
    current_time= datetime.datetime.strptime(current,"%Y-%m-%d %H:%M:%S")
    day=current_time.day
    hour=current_time.hour
    min=current_time.minute
    Time_min=hour*60+min
    interval=math.ceil(Time_min/30)-1
    taxi_halfhour_pick[day-1,interval,np.int(taxi_trip_05['PULocationGrid_ID'][i])]=taxi_halfhour_pick[day-1,interval,np.int(taxi_trip_05['PULocationGrid_ID'][i])]+1
    taxi_halfhour_drop[day-1,interval,np.int(taxi_trip_05['DOLocationGrid_ID'][i])]=taxi_halfhour_drop[day-1,interval,np.int(taxi_trip_05['DOLocationGrid_ID'][i])]+1

taxi_halfhour_pick= taxi_halfhour_pick.reshape([31,48,27,27])#生成数组保存每组速度
taxi_halfhour_drop= taxi_halfhour_drop.reshape([31,48,27,27])#

In [129]:
#映射到三维当中去
taxi_halfhour_pick1= np.zeros([1488,27,27])
taxi_halfhour_drop1= np.zeros([1488,27,27])
for i in range(0,31):
    for j in range(0,48):
        taxi_halfhour_pick1[i*48+j,:,:]=taxi_halfhour_pick[i,j,:,:]
        taxi_halfhour_drop1[i*48+j,:,:]=taxi_halfhour_drop[i,j,:,:]
for i in range(1488):
    taxi_halfhour_pick1[i,0,0]=0
    taxi_halfhour_drop1[i,0,0]=0

In [57]:
import pandas as pd
import numpy as np

In [62]:
taxi_data=pd.DataFrame(pd.read_csv('E:/data ming/accident_prediction/NYC_data/taxi_1705.csv'))

c:\users\dell\appdata\local\programs\python\python36\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (1,9,10,11,12,13) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [64]:
taxi_data

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Day,Unnamed: 4,pick_time,Unnamed: 6,Unnamed: 7,drop_time,Unnamed: 9,Unnamed: 10,Unnamed: 11,pick_ID,drop_ID
0,1.0,1,5.0,1.0,0.00000,0.00000,1.0,0.01757,25.30000,1,17.1,63.35,530,383
1,2.0,1,5.0,1.0,0.00000,0.00000,1.0,0.01576,22.70000,1,9.9,43.26,283,383
2,3.0,2,5.0,1.0,0.00000,0.00000,1.0,0.01924,27.70000,1,4.4,20.8,383,280
3,6.0,1,5.0,1.0,0.00001,0.01667,1.0,0.01147,16.51667,1,3.6,16.3,356,304
4,7.0,1,5.0,1.0,0.00001,0.01667,1.0,0.00692,9.96667,1,1.8,10.3,383,305
5,8.0,1,5.0,1.0,0.00002,0.03333,1.0,0.01307,18.81667,1,4.1,17.3,383,357
6,12.0,2,5.0,1.0,0.00002,0.03333,1.0,0.00810,11.66667,2,2.52,11.8,304,383
7,13.0,1,5.0,1.0,0.00003,0.05000,1.0,0.00304,4.38333,2,0.7,7.55,384,385
8,14.0,2,5.0,1.0,0.00003,0.05000,1.0,0.01182,17.01667,5,8.41,35.56,283,383
9,15.0,2,5.0,1.0,0.00003,0.05000,1.0,0.00829,11.93333,1,2.91,14.76,303,357
10,16.0,1,5.0,1.0,0.00006,0.08333,1.0,0.00209,3.01667,1,0.3,5.3,357,383
11,17.0,2,5.0,1.0,0.00006,0.08333,1.0,0.01122,16.15000,2,3.64,18.96,330,251
12,18.0,1,5.0,1.0,0.00007,0.10000,1.0,0.00729,10.50000,3,3.3,13.8,283,280
13,19.0,2,5.0,1.0,0.00007,0.10000,1.0,0.00124,1.78333,1,0.18,4.3,385,385
14,20.0,2,5.0,1.0,0.00008,0.11667,1.0,0.00623,8.96667,1,2.52,11.3,330,331
15,21.0,2,5.0,1.0,0.00008,0.11667,1.0,0.01097,15.80000,3,2.31,16.62,358,383
16,22.0,1,5.0,1.0,0.00009,0.13333,1.0,0.01959,28.21667,1,12,43.06,331,310
17,23.0,1,5.0,1.0,0.00009,0.13333,1.0,0.00537,7.73333,2,1.3,8.8,440,439
18,24.0,2,5.0,1.0,0.00009,0.13333,1.0,0.00659,9.48333,1,2.36,12.96,383,383
19,25.0,1,5.0,1.0,0.00012,0.16667,1.0,0.00965,13.90000,2,3.4,15.8,331,383
20,26.0,1,5.0,1.0,0.00012,0.16667,1.0,0.00162,2.33333,1,0.4,6.6,170,383
21,27.0,1,5.0,1.0,0.00012,0.16667,1.0,0.00892,12.85000,1,2.5,15.35,330,358
22,28.0,2,5.0,1.0,0.00012,0.16667,1.0,0.00999,14.38333,5,7.64,24.3,383,144
23,29.0,1,5.0,1.0,0.00013,0.18333,1.0,0.00397,5.71667,1,1.5,8.3,303,330
24,30.0,1,5.0,1.0,0.00013,0.18333,1.0,0.01699,24.46667,1,11.8,41.06,283,64
25,31.0,2,5.0,1.0,0.00013,0.18333,1.0,0.00635,9.15000,1,1.62,10.8,467,439
26,32.0,2,5.0,1.0,0.00013,0.18333,1.0,0.00649,9.35000,1,1.6,9.8,330,331
27,33.0,1,5.0,1.0,0.00015,0.21667,1.0,0.00598,8.61667,1,1.5,10.3,356,358
28,34.0,2,5.0,1.0,0.00016,0.23333,1.0,0.00350,5.03333,1,0.69,7.88,383,383
29,35.0,2,5.0,1.0,0.00016,0.23333,1.0,0.00881,12.68333,1,4.18,15.3,383,251
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048544,940617.0,1,5.0,21.0,0.41756,601.28333,21.0,0.42719,615.15000,1,1.8,11.3,286,302
1048545,940618.0,2,5.0,21.0,0.41756,601.28333,21.0,0.42668,614.41667,5,2.42,14.16,331,302
1048546,940619.0,2,5.0,21.0,0.41756,601.28333,21.0,0.42395,610.48333,5,1.54,8.8,383,383
1048547,940620.0,2,5.0,21.0,0.41756,601.28333,21.0,0.42030,605.23333,1,0.74,5.8,358,331
1048548,940621.0,2,5.0,21.0,0.41756,601.28333,21.0,0.42683,614.63333,5,1.89,11.3,331,383
1048549,940622.0,1,5.0,21.0,0.41757,601.30000,21.0,0.42676,614.53333,1,4.1,17.8,383,331
1048550,940623.0,1,5.0,21.0,0.41757,601.30000,21.0,0.42172,607.28333,2,1.2,7.3,383,330
1048551,940624.0,2,5.0,21.0,0.41757,601.30000,21.0,0.42203,607.71667,1,1.3,7.3,330,383
1048552,940625.0,2,5.0,21.0,0.41757,601.30000,21.0,0.45255,651.66667,1,5.93,39.36,383,383
1048553,940626.0,1,5.0,21.0,0.41758,601.31667,21.0,0.42249,608.38333,1,2.1,11.15,305,331
1048554,940627.0,1,5.0,21.0,0.41758,601.31667,21.0,0.43090,620.50000,1,5.2,20.8,383,383
1048555,940628.0,1,5.0,21.0,0.41758,601.31667,21.0,0.42522,612.31667,1,6.6,20.3,383,383
1048556,940629.0,2,5.0,21.0,0.41758,601.31667,21.0,0.42463,611.46667,1,2.32,12.36,383,383
1048557,940630.0,2,5.0,21.0,0.41758,601.31667,21.0,0.42313,609.30000,1,1.55,7.8,331,330
1048558,940631.0,2,5.0,21.0,0.41758,601.31667,21.0,0.42709,615.01667,1,1.92,13.56,383,383
1048559,940632.0,2,5.0,21.0,0.41758,601.31667,21.0,0.43010,619.35000,1,4.43,20.76,383,383
1048560,940633.0,1,5.0,21.0,0.41759,601.33333,21.0,0.42135,606.75000,1,0.6,7.3,331,383
1048561,940634.0,2,5.0,21.0,0.41759,601.33333,21.0,0.42961,618.63333,1,7.12,27.36,304,383
1048562,940635.0,1,5.0,21.0,0.41760,601.35000,21.0,0.42524,612.35000,2,2.9,15.35,384,383
1048563,940636.0,2,5.0,21.0,0.41760,601.35000,21.0,0.42146,606.90000,1,1.07,7.56,383,251
1048564,940637.0,1,5.0,21.0,0.41762,601.36667,21.0,0.42262,608.56667,1,1.3,7.8,331,385
1048565,940638.0,2,5.0,21.0,0.41762,601.36667,21.0,0.42229,608.10000,1,1.71,8.3,383,383
1048566,940639.0,2,5.0,21.0,0.41762,601.36667,21.0,0.42476,611.65000,1,1.18,8.8,383,286
1048567,940640.0,2,5.0,21.0,0.41762,601.36667,21.0,0.42964,618.68333,6,3.33,15.3,383,383
1048568,940641.0,2,5.0,21.0,0.41762,601.36667,21.0,0.42711,615.03333,1,2.14,14.75,330,383
1048569,940642.0,2,5.0,21.0,0.41762,601.36667,21.0,0.42469,611.55000,1,2.41,12.96,383,383
1048570,940643.0,1,5.0,21.0,0.41763,601.38333,21.0,0.42231,608.13333,1,1.3,9.36,383,383
1048571,940644.0,1,5.0,21.0,0.41763,601.38333,21.0,0.42264,608.60000,1,1.2,9.35,224,198
1048572,940645.0,1,5.0,21.0,0.41763,601.38333,21.0,0.42943,618.38333,1,8.4,37.86,383,283
1048573,NaN,VendorID,NaN,NaN,NaN,0.00000,NaN,NaN,0.00000,passenger_count,trip_distance,total_amount,PULocationGrid_ID,DOLocationGrid_ID

In [63]:
#对一个月的数据做处理 每天30min一个interval 一天48个 31*48
import collections
taxi_halfhour_pick= np.zeros([31,48,27,27])#生成数组保存每组速度
taxi_halfhour_drop= np.zeros([31,48,27,27])#
ss=np.int32(0)
for ii in range(1,32):
    taxi_dataset=taxi_data[taxi_data['Day']==np.float(ii)]
    count_half_hour=np.zeros(49)  #生成数组保存每组的个数，每半小时一个为48 下面为30分钟 27*27是网格大小
    for j in range(0,48):# 分段，计算每个interval中有几条记录 然后每次索引时用这个数据来控制归类的数据条目段
        ab=np.where((taxi_dataset['pick_time']>=30.0*j)&(taxi_dataset['pick_time']<30*j+30),1,0)
        count_half_hour[j+1]=collections.Counter(ab)[1]
    for j in range(0,48):
        #speed_value_ingrid=np.zeros(729)
        count_pick_id=np.zeros(729)
        count_drop_id=np.zeros(729)
        for i in range(ss,ss+np.int32(count_half_hour[j+1])):
           #print(ii,i,j)
            count_pick_id[np.int(taxi_dataset['pick_ID'][i])]=count_pick_id[np.int(taxi_dataset['pick_ID'][i])]+1
            count_drop_id[np.int(taxi_dataset['drop_ID'][i])]=count_pick_id[np.int(taxi_dataset['drop_ID'][i])]+1
        ss=np.int32(ss)+np.int32(count_half_hour[j+1])#ss为总的累计值
        #print(ss)
       
        taxi_halfhour_pick[ii-1,j,:,:]=count_pick_id.reshape(27,27)
        taxi_halfhour_drop[ii-1,j,:,:]=count_drop_id.reshape(27,27)
    print(ss)

#映射到三维当中去
taxi_halfhour_pick1= np.zeros([1488,27,27])
taxi_halfhour_drop1= np.zeros([1488,27,27])
for i in range(0,31):
    for j in range(0,48):
        taxi_halfhour_pick1[i*48+j,:,:]=taxi_halfhour_pick[i,j,:,:]
        taxi_halfhour_drop1[i*48+j,:,:]=taxi_halfhour_drop[i,j,:,:]

303358
635923
973099
1003371
1003371
1003371
1003371
1003371
1003371
1003371
1003371
1003371
1003371
1003371
1003371
1003371
1003373
1003375
1003375
1003375
1048573
1048573
1048573
1048573
1048573
1048573
1048573
1048573
1048573
1048573
1048573

In [ ]:
for i in range(1488):
    taxi_halfhour_pick1[i,0,0]=0
    taxi_halfhour_drop1[i,0,0]=0

In [130]:
# taxi_halfhour_pick1= np.zeros([1488,27,27])
# taxi_halfhour_drop1= np.zeros([1488,27,27])
# for i in range(0,31):
#     for j in range(0,48):
#         taxi_halfhour_pick1[i*48+j,:,:]=taxi_halfhour_pick[i,j,:,:]
#         taxi_halfhour_drop1[i*48+j,:,:]=taxi_halfhour_drop[i,j,:,:]
        
taxi_halfhour_pick1_05=np.zeros([354,1488])
taxi_halfhour_drop1_05=np.zeros([354,1488])
for i in range(1488):
    taxi_halfhour_pick1_05[:,i]=transfer_354(taxi_halfhour_pick1[i,:,:])
    taxi_halfhour_drop1_05[:,i]=transfer_354(taxi_halfhour_drop1[i,:,:])
np.save('taxi_halfhour_pick_05.npy',taxi_halfhour_pick1_05)
np.save('taxi_halfhour_drop_05.npy',taxi_halfhour_drop1_05)

In [ ]:
#taxi_trips 划分到网格 制作矩阵

In [147]:
Interval=1488 
DAY=31
#Interval=1440
#DAY=30
#Interval=1344
#DAY=28

In [133]:
taxi_trip_04

,Dispatching_base_num,Pickup_DateTime,DropOff_datetime,PUlocationID,DOlocationID
0,B00001,2017-01-01 00:30:00,NaN,NaN,NaN
1,B00001,2017-01-01 00:30:00,NaN,NaN,NaN
2,B00008,2017-01-01 00:50:00,NaN,NaN,NaN
3,B00009,2017-01-01 00:10:00,NaN,NaN,NaN
4,B00009,2017-01-01 00:50:00,NaN,NaN,NaN
5,B00014,2017-01-01 00:10:00,NaN,NaN,NaN
6,B00014,2017-01-01 00:05:00,NaN,NaN,NaN
7,B00014,2017-01-01 00:10:00,NaN,NaN,NaN
8,B00014,2017-01-01 00:50:00,NaN,NaN,NaN
9,B00014,2017-01-01 00:15:00,NaN,NaN,NaN
10,B00014,2017-01-01 00:05:00,NaN,NaN,NaN
11,B00029,2017-01-01 00:56:00,NaN,174.0,NaN
12,B00029,2017-01-01 00:01:00,NaN,3.0,NaN
13,B00029,2017-01-01 00:16:00,NaN,51.0,NaN
14,B00029,2017-01-01 00:22:00,NaN,3.0,NaN
15,B00029,2017-01-01 00:46:00,NaN,185.0,NaN
16,B00037,2017-01-01 00:34:00,NaN,NaN,NaN
17,B00037,2017-01-01 00:42:00,NaN,NaN,NaN
18,B00037,2017-01-01 00:57:00,NaN,NaN,NaN
19,B00037,2017-01-01 00:36:00,NaN,NaN,NaN
20,B00037,2017-01-01 00:24:00,NaN,NaN,NaN
21,B00037,2017-01-01 00:55:00,NaN,NaN,NaN
22,B00037,2017-01-01 00:12:00,NaN,NaN,NaN
23,B00037,2017-01-01 00:24:00,NaN,NaN,NaN
24,B00037,2017-01-01 00:48:00,NaN,NaN,NaN
25,b00056,2017-01-01 00:14:00,NaN,NaN,NaN
26,b00056,2017-01-01 00:21:00,NaN,NaN,NaN
27,b00056,2017-01-01 00:12:00,NaN,NaN,NaN
28,b00056,2017-01-01 00:57:00,NaN,NaN,NaN
29,b00056,2017-01-01 00:45:00,NaN,NaN,NaN
...,...,...,...,...,...
13657182,B02914,2017-01-31 23:34:19,NaN,NaN,NaN
13657183,B02914,2017-01-31 23:19:14,NaN,NaN,NaN
13657184,B02914,2017-01-31 23:00:49,NaN,NaN,NaN
13657185,B02914,2017-01-31 23:04:59,NaN,NaN,NaN
13657186,B02914,2017-01-31 23:13:49,NaN,NaN,NaN
13657187,B02914,2017-01-31 23:44:10,NaN,NaN,NaN
13657188,B02914,2017-01-31 23:12:16,NaN,NaN,NaN
13657189,B02914,2017-01-31 23:48:03,NaN,NaN,NaN
13657190,B02924,2017-01-31 23:59:00,NaN,NaN,NaN
13657191,B02924,2017-01-31 23:46:00,NaN,NaN,NaN
13657192,B02924,2017-01-31 23:59:00,NaN,NaN,NaN
13657193,B02924,2017-01-31 23:59:00,NaN,NaN,NaN
13657194,B02924,2017-01-31 23:59:00,NaN,NaN,NaN
13657195,B02924,2017-01-31 23:59:00,NaN,NaN,NaN
13657196,B02924,2017-01-31 23:59:00,NaN,NaN,NaN
13657197,B02924,2017-01-31 23:59:00,NaN,NaN,NaN
13657198,B02924,2017-01-31 23:59:00,NaN,NaN,NaN
13657199,B02930,2017-01-31 23:25:00,NaN,NaN,NaN
13657200,B02942,2017-01-31 23:49:11,NaN,NaN,NaN
13657201,B02944,2017-01-31 23:14:00,NaN,216.0,0.0
13657202,B02944,2017-01-31 23:53:00,NaN,205.0,0.0
13657203,B02944,2017-01-31 23:21:00,NaN,130.0,0.0
13657204,B02947,2017-01-31 23:59:00,NaN,NaN,NaN
13657205,B02956,2017-01-31 23:00:00,NaN,NaN,NaN
13657206,B02967,2017-01-31 23:00:00,NaN,NaN,NaN
13657207,B02970,2017-01-31 23:09:00,NaN,NaN,NaN
13657208,B02996,2017-01-31 23:04:00,NaN,NaN,NaN
13657209,B02996,2017-01-31 23:01:00,NaN,NaN,NaN
13657210,B03002,2017-01-31 23:59:00,NaN,NaN,NaN
13657211,B03002,2017-01-31 23:59:00,NaN,NaN,NaN

In [142]:
import numpy as np
import pandas as pd
taxi_trip_04=pd.read_csv(r'E:\data ming\accident_prediction\NYC_data\taxi_data\green_tripdata_2017-01.csv') #改名字！

path="E:/data ming/accident_prediction/NYC_data/taxi_data/taxi_loca11.csv"
all_data=pd.DataFrame(pd.read_csv(path))
index_num=np.zeros([266,2]) #建立空矩阵 存放索引号-索引内容
index_num[all_data['LocationID'],0]=all_data['LocationID'] #填充索引内容
index_num[all_data['LocationID'],1]=all_data['grid_id'] #填充索引内容

#path="E:/data ming/accident_prediction/NYC_data/taxi_data/yellow_tripdata_2017-01.csv"
taxi_data=taxi_trip_04
#索引成功后的数组
PULocationGrid_ID=[]
DOLocationGrid_ID=[]
for i in range(0,len(taxi_data)):
  #  try:
        PULocationGrid_ID.append(index_num[np.int(taxi_data['PULocationID'][i]),1])
        DOLocationGrid_ID.append(index_num[taxi_data['DOLocationID'][i],1])
 #   except:
        #PULocationGrid_ID.append(0)
        #DOLocationGrid_ID.append(index_num[taxi_data['DOLocationID'][i],1])
#保存为原矩阵中的内容，增加两列。
taxi_data['PULocationGrid_ID']=PULocationGrid_ID  
#taxi_data['DOLocationGrid_ID']=DOLocationGrid_ID  
#将结果输出
Path='E:/data ming/accident_prediction/NYC_data/green_taxi_1701.csv'
pd.DataFrame(taxi_data).to_csv(Path)#直接输出网格index #改名字！

In [144]:
taxi_data['DOLocationGrid_ID']=DOLocationGrid_ID

In [145]:
taxi_data

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,PULocationGrid_ID,DOLocationGrid_ID
0,2,2017/1/1 0:01,2017/1/1 0:11,N,1,42,166,383.0,197.0
1,2,2017/1/1 0:03,2017/1/1 0:09,N,1,75,74,383.0,383.0
2,2,2017/1/1 0:04,2017/1/1 0:12,N,1,82,70,336.0,283.0
3,2,2017/1/1 0:01,2017/1/1 0:14,N,1,255,232,383.0,384.0
4,2,2017/1/1 0:00,2017/1/1 0:18,N,1,166,239,197.0,383.0
5,2,2017/1/1 0:00,2017/1/1 0:13,N,1,179,226,280.0,334.0
6,2,2017/1/1 0:02,2017/1/1 0:26,N,1,74,167,383.0,173.0
7,2,2017/1/1 0:15,2017/1/1 0:28,N,1,112,37,360.0,383.0
8,2,2017/1/1 0:06,2017/1/1 0:11,N,1,36,37,383.0,383.0
9,2,2017/1/1 0:14,2017/1/1 0:28,N,1,127,174,91.0,66.0
10,2,2017/1/1 0:01,2017/1/1 0:09,N,1,41,238,198.0,383.0
11,2,2017/1/1 0:31,2017/1/1 0:52,N,1,97,228,439.0,383.0
12,2,2017/1/1 0:01,2017/1/1 0:22,N,1,255,26,383.0,546.0
13,2,2017/1/1 0:00,2017/1/1 0:09,N,1,70,173,283.0,310.0
14,2,2017/1/1 0:03,2017/1/1 0:18,N,1,255,40,383.0,465.0
15,2,2017/1/1 0:03,2017/1/1 0:03,N,1,82,260,336.0,335.0
16,2,2017/1/1 0:00,2017/1/1 0:00,N,5,36,36,383.0,383.0
17,2,2017/1/1 0:01,2017/1/1 0:11,N,1,7,223,280.0,383.0
18,2,2017/1/1 0:26,2017/1/1 0:38,N,1,256,106,383.0,465.0
19,2,2017/1/1 0:49,2017/1/1 1:00,N,1,181,228,466.0,383.0
20,2,2017/1/1 0:10,2017/1/1 0:34,N,1,112,107,360.0,331.0
21,2,2017/1/1 0:02,2017/1/1 0:14,N,1,129,56,309.0,337.0
22,2,2017/1/1 0:01,2017/1/1 0:34,N,1,112,152,360.0,197.0
23,2,2017/1/1 0:00,2017/1/1 0:12,N,1,91,188,576.0,521.0
24,2,2017/1/1 0:00,2017/1/1 0:30,N,1,228,140,383.0,383.0
25,2,2017/1/1 0:04,2017/1/1 0:12,N,1,126,159,201.0,383.0
26,2,2017/1/1 0:02,2017/1/1 0:16,N,1,97,181,439.0,466.0
27,2,2017/1/1 0:02,2017/1/1 0:12,N,1,129,173,309.0,310.0
28,2,2017/1/1 0:01,2017/1/1 0:07,N,1,41,43,198.0,251.0
29,2,2017/1/1 0:02,2017/1/1 0:19,N,1,37,63,383.0,471.0
...,...,...,...,...,...,...,...,...,...
1048544,2,2017/1/31 11:42,2017/1/31 12:12,N,1,66,164,412.0,383.0
1048545,2,2017/1/31 11:33,2017/1/31 12:06,N,1,65,37,383.0,383.0
1048546,2,2017/1/31 11:05,2017/1/31 11:24,N,1,42,239,383.0,383.0
1048547,2,2017/1/31 11:39,2017/1/31 11:44,N,1,41,42,198.0,383.0
1048548,2,2017/1/31 11:33,2017/1/31 11:51,N,1,74,166,383.0,197.0
1048549,2,2017/1/31 11:20,2017/1/31 11:23,N,1,223,138,383.0,283.0
1048550,2,2017/1/31 11:42,2017/1/31 11:49,N,1,116,42,170.0,383.0
1048551,2,2017/1/31 11:52,2017/1/31 12:01,N,1,66,65,412.0,383.0
1048552,2,2017/1/31 11:14,2017/1/31 11:31,N,1,74,116,383.0,170.0
1048553,2,2017/1/31 11:29,2017/1/31 11:37,N,1,116,244,170.0,144.0
1048554,2,2017/1/31 11:20,2017/1/31 11:37,N,1,75,166,383.0,197.0
1048555,2,2017/1/31 11:38,2017/1/31 11:44,N,1,166,238,197.0,383.0
1048556,2,2017/1/31 11:27,2017/1/31 11:42,N,1,256,37,383.0,383.0
1048557,2,2017/1/31 11:15,2017/1/31 11:29,N,1,152,142,197.0,383.0
1048558,2,2017/1/31 11:50,2017/1/31 11:57,N,1,75,236,383.0,383.0
1048559,2,2017/1/31 11:59,2017/1/31 12:07,N,1,236,75,383.0,383.0
1048560,2,2017/1/31 11:34,2017/1/31 11:45,N,1,181,257,466.0,493.0
1048561,2,2017/1/31 11:19,2017/1/31 11:26,N,1,166,152,197.0,197.0
1048562,2,2017/1/31 11:41,2017/1/31 12:03,N,1,74,141,383.0,383.0
1048563,2,2017/1/31 11:48,2017/1/31 11:51,N,1,17,17,0.0,0.0
1048564,2,2017/1/31 11:45,2017/1/31 11:56,N,1,247,147,172.0,173.0
1048565,2,2017/1/31 11:19,2017/1/31 12:06,N,1,7,68,280.0,330.0
1048566,2,2017/1/31 11:12,2017/1/31 11:14,N,1,18,18,93.0,93.0
1048567,2,2017/1/31 11:34,2017/1/31 11:53,N,1,116,43,170.0,251.0
1048568,2,2017/1/31 11:53,2017/1/31 11:59,N,1,188,188,521.0,521.0
1048569,2,2017/1/31 11:50,2017/1/31 11:57,N,1,85,71,383.0,549.0
1048570,2,2017/1/31 11:46,2017/1/31 12:04,N,1,65,49,383.0,440.0
1048571,2,2017/1/31 11:47,2017/1/31 12:05,N,1,42,41,383.0,198.0
1048572,2,2017/1/31 11:45,2017/1/31 11:54,N,1,82,129,336.0,309.0
1048573,2,2017/1/31 11:57,2017/1/31 12:23,N,1,75,142,383.0,383.0

In [150]:
import collections
import math
taxi_halfhour_pick= np.zeros([DAY,48,729])#生成数组保存每组速度
taxi_halfhour_drop= np.zeros([DAY,48,729])#
for i in range(len(taxi_data)):
    current_pick=taxi_data['lpep_pickup_datetime'][i]  
    #print(current)
    current_time= datetime.datetime.strptime(current_pick,"%Y/%m/%d %H:%M")
    day=current_time.day
    hour=current_time.hour
    min=current_time.minute
    Time_min=hour*60+min
    interval_pick=math.ceil(Time_min/30)-1
    
    current_drop=taxi_data['lpep_dropoff_datetime'][i]  
    #print(current)
    current_time= datetime.datetime.strptime(current_drop,"%Y/%m/%d %H:%M")
    day=current_time.day
    hour=current_time.hour
    min=current_time.minute
    Time_min=hour*60+min
    interval_drop=math.ceil(Time_min/30)-1
    taxi_halfhour_pick[day-1,interval_pick,np.int(taxi_data['PULocationGrid_ID'][i])]=taxi_halfhour_pick[day-1,interval_pick,np.int(taxi_data['PULocationGrid_ID'][i])]+1
    taxi_halfhour_drop[day-1,interval_drop,np.int(taxi_data['DOLocationGrid_ID'][i])]=taxi_halfhour_drop[day-1,interval_drop,np.int(taxi_data['DOLocationGrid_ID'][i])]+1

taxi_halfhour_pick= taxi_halfhour_pick.reshape([DAY,48,27,27])#生成数组保存每组速度
taxi_halfhour_drop= taxi_halfhour_drop.reshape([DAY,48,27,27])#

In [ ]:
#映射到三维当中去
taxi_halfhour_pick1= np.zeros([Interval,27,27])
taxi_halfhour_drop1= np.zeros([Interval,27,27])
for i in range(0,DAY):
    for j in range(0,48):
        taxi_halfhour_pick1[i*48+j,:,:]=taxi_halfhour_pick[i,j,:,:]
        taxi_halfhour_drop1[i*48+j,:,:]=taxi_halfhour_drop[i,j,:,:]
for i in range(Interval):
    taxi_halfhour_pick1[i,0,0]=0
    taxi_halfhour_drop1[i,0,0]=0

In [ ]:
index_road=pd.DataFrame(pd.read_csv("E:/data ming/accident_prediction/NYC_data/Experimental_data/index_road.csv"))
index_road=np.array(index_road)[:,0]

def transfer_354(A):
    B1=np.zeros([354])
    A=np.array(A).reshape([729])
    for i in range(354):
        B1[i]=A[index_road[i]]
    return B1


taxi_halfhour_pick1_04=np.zeros([354,Interval])
taxi_halfhour_drop1_04=np.zeros([354,Interval])
for i in range(Interval):
    taxi_halfhour_pick1_04[:,i]=transfer_354(taxi_halfhour_pick1[i,:,:])
    taxi_halfhour_drop1_04[:,i]=transfer_354(taxi_halfhour_drop1[i,:,:])
np.save('taxi_pick_01.npy',taxi_halfhour_pick1_04)
np.save('taxi_drop_01.npy',taxi_halfhour_drop1_04)